【Hackathon No.153】PaddleRS 英文文档
PaddlePaddle/PaddleRS pull request #113
Opened 2023-03-20 11:37 UTC by lizechng

### PR types
Others

### PR changes
Others

### Description
- 将 PaddleRS docs 目录中包含的文档内容翻译为英文，并形成相应英文文档
- 为 PaddleRS tutorials 目录中的示例脚本添加英文注释

2023-03-20 12:49 UTC, Bobholamovic requested changes
感谢你为PaddleRS贡献文档。我留了一些小建议，请先看看~ 目前的review还不完整，待这次修改完成后我会进一步进行review。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +This guide starts with the steps necessary to contribute code to PaddleRS, and then goes into detail on new file self-review, code style specification, and testing steps.
`steps necessary` -> `necessary steps`

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +This guide starts with the steps necessary to contribute code to PaddleRS, and then goes into detail on new file self-review, code style specification, and testing steps.
`new file self-review` -> `self-inspection on newly added files`

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +### 1 Code contribution steps
标题每个实词的首字母需要大写。
请同步修改PR中其他部分。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +PaddleRS uses [git](https://git-scm.com/doc) as a version control tool and is hosted on GitHub. This means that you need to be familiar with git before contributing code, and understand [pull request
`, and understand`这半句建议拆成一个独立的句子。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +1. fork the official PaddleRS repository on GitHub, clone the code locally, and pull up the latest version of the develop branch.
句子的首字母需要大写。
请同步检查并修改PR中的类似错误。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +2. Write code according to [dev Guide](dev/dev_guide.md) (it is recommended to develop on a new branch of functionality).
`branch of functionality` -> `feature branch`

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +3. Install pre-commit hooks to perform code style checks before each commit. Refer to [Code style specification](#3-Code style specification)。
请同步检查整个PR提交，将全角标点符号替换为半角标点符号。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +4. Write unit tests for the new code and make sure all the tests run. Refer to[Test related steps](#4-Test related steps)。
请确认`all the tests run` 的表述与中文文档是否对应。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +If you contribute code that uses a third-party library that PaddleRS does not currently rely on, please do so when you submit your PR and explain why you need to use that third-party library.
此句疑似翻译错误。`do so` 指的是？

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +### 2 Added file self-check
`Self-check on Added Files`

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +Unlike code style specifications, pre-commit hooks do not enforce the rules described in this section, so it is up to the developer to check.
这里是不是翻译反了呀？

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +1. Python standard library;
加复数。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +2. Third-party libraries installed through package managers such as' pip '(note that `paddle` is a third-party library, but `paddlers` is not itself a third-party library);
`' pip '`疑似格式有误

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +There is a blank line between import statements of different types. The file should not contain import statements for unused packages or modules. In addition, if the length of the imported statements
`There is` -> `There should be`

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +PaddleRS' code style specification is basically the same as the [Google Python Style specification](https://zh-google-styleguide.readthedocs.io/en/latest/google-python-styleguide/python_style_rules/)
`but` -> `except that`

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +### 3 Code style specification
`more important` 是否翻译有误？

2023-03-20 12:49 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +- Parentheses: Parentheses can be used for line concatenation, but do not use unnecessary parentheses in `if` judgments.
请确认` in if judgments`的表达是否准确。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/apis/data_en.md
> +In PaddleRS, all datasets are inherit from the parent class [`BaseDataset`](https://github.com/PaddlePaddle/PaddleRS/blob/develop/paddlers/datasets/base.py)。
`are inherit` -> `inherit`

2023-03-20 12:49 UTC, Bobholamovic commented on docs/intro/model_zoo_en.md
> +
需要链接到英文文档

2023-03-20 12:49 UTC, Bobholamovic commented on docs/intro/transforms_en.md
> +In the actual model training process, it is often necessary to combine a variety of data preprocessing and data enhancement strategies. PaddleRS provides `paddlers.transforms.Compose` operator to eas
`The specific usage of ` 前面加`For`

2023-03-20 12:49 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`file_list`|`str`|file list path. file list is a text file, in which each line contains the path infomation of sample.The specific requirements of `CDDataset` on the file list are listed below.||
请注意句首字母大写。请同步检查其他部分，后续不再重复。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`file_list`|`str`|file list path. file list is a text file, in which each line contains the path infomation of sample.The specific requirements of `CDDataset` on the file list are listed below.||
请注意标点符号之后空一格。
请同步检查PR中的其它部分。后续不再重复。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`num_workers`|`int` \| `str`|The number of worker processes used when loading data. If it is set to `'auto'`, the following rules determine the number of processes to use:When the number of CPU core
这里翻译好像不太对，请检查。另外请同步检查PR中其它涉及`num_workers`解释的部分。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`with_seg_labels`|`bool`|Specify this option as `True` when the dataset contains split labels for each phase.|`False`|
`split labels`翻译是否准确？

2023-03-20 12:49 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`binarize_labels`|`bool`|If it is `True`, the change label (and split label) is binarized after all data transformation operators except `Arrange` are processed. For example, binarize a tag with the
一个像素点为一个`label`，所以`label`应该是复数（或者用`label image`）。

2023-03-20 12:49 UTC, Bobholamovic commented on docs/apis/data_en.md
> +The requirments of `CDDataset` for the file list are as follows:
typo: `requirments`，请同步检查PR中其他部分。

2023-03-21 12:40 UTC, lizechng commented
您好，已进行修改

2023-03-21 12:49 UTC, Bobholamovic commented
我注意到好像还没有修改完全~ 建议可以逐条回复review意见，以免遗漏。

2023-03-23 11:05 UTC, lizechng commented on docs/CONTRIBUTING_en.md
> +Unlike code style specifications, pre-commit hooks do not enforce the rules described in this section, so it is up to the developer to check.
- 与代码风格规范不同，pre-commit钩子并不对本小节所阐述的规则做强制要求，因此需要开发者自行检查。

- Unlike code style specifications, pre-commit hooks do not enforce the rules described in this section, so it is up to the developer to check.

这里是否我理解的存在问题，我理解的是pre-commit钩子检查代码风格规范，但对版权信息和模块导入顺序等不做检查

2023-03-23 11:08 UTC, lizechng commented on docs/CONTRIBUTING_en.md
> +- Parentheses: Parentheses can be used for line concatenation, but do not use unnecessary parentheses in `if` judgments.
- 括号可以用于行连接，但是不要在`if`判断中使用没有必要的括号
- but do not use unnecessary parentheses in `if` judgments.

in `if` judgments中 `if` 指python判断语句，这样翻译是否需要修改

2023-03-23 11:12 UTC, lizechng commented on docs/intro/model_zoo_en.md
> +
# Model Zoo

PaddleRS' base model library comes from the Paddle-CV suite: [PaddleClas](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/en/algorithm_introduction/ImageNet_models_en.md), [PaddleSeg](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/docs/model_zoo_overview.md), [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/README_en.md#Model-libraries), [PaddleGAN](https://github.com/PaddlePaddle/PaddleGAN/blob/develop/README.md#Model-Tutorial). In addition, PaddleRS also contains a series of remote sensing feature models, which can be used for remote sensing image segmentation and change detection.

英文文档链接在正文第一行

2023-03-23 11:18 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +Unlike code style specifications, pre-commit hooks do not enforce the rules described in this section, so it is up to the developer to check.
Sorry，应该是我当时看走眼了，这个翻译是准确的~

2023-03-23 11:27 UTC, lizechng commented
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1146022384

- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1146027435

这两个不知道目前的翻译是否可以？其余均已按照意见完成修改~

2023-03-23 12:22 UTC, Bobholamovic commented on docs/intro/model_zoo_en.md
> +
`Paddle-CV suite` -> `PaddleCV development kits`

2023-03-23 12:24 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +- Parentheses: Parentheses can be used for line concatenation, but do not use unnecessary parentheses in `if` judgments.
建议把`judgements`改为`conditions`

2023-03-23 12:40 UTC, lizechng commented
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1146106642
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1146104420

这两处已修改~

2023-03-24 07:14 UTC, Bobholamovic requested changes
留了一些意见

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +This guide starts with the necessary steps to contribute code to PaddleRS, and then goes into detail on self-inspection on newly added files, code style specification, and testing steps.
`detail` -> `details`

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +1. Fork the official PaddleRS repository on GitHub, clone the code locally, and pull up the latest version of the develop branch.
`pull up` -> `pull`

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +5. Create a new PR for your branch to ensure that the CLA protocol is signed and the CI/CE passes. After that, a PaddleRS team member will review the code you contributed.
`to ensure` -> `and ensure`

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +If you contribute code that uses a third-party library that PaddleRS does not currently rely on, please explain when you submit your PR and explain why you need to use this third-party library.
`your PR. Also, you should explain why this third-party library should be used.

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +All global import statements must be at the beginning of the module, after the copyright information. Import packages or modules in the following order:
`after` -> `right after`

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +- Exceptions: Throw and catch exceptions with as specific an Exception type as possible, and almost never use the base class `Exception` (unless the purpose is to catch any exception of any type).
`Exception type` `E`不需要大写

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +- Comments: All comments are written in English. All apis provided to users must have docstrings added and have at least two sections, "API Function Description" and "API Parameters." Surround a docs
`"API Parameters".` 句号在引号之后

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +
分号之后不需要首字母大写

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +2. Define a Test class for the new Model that inherits from `Test{task name}Model` and sets its `MODEL_CLASS` property to the new model, following the example already in the file.
此处`Model`应该不需要首字母大写

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +- If you write the data preprocessing/enhancement operator (inherited from `paddlers.transforms.operators.Transform`), all the necessary to construct the operator input parameters have default values
`enhancement` -> `augmentation`
请同步检查并修改PR中其它部分，将『数据增强』统一翻译为『data augmentation』。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +## Contribution Case
`Contribution Case` -> `Contribute an Example`

2023-03-24 07:14 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +### 2 Self-check on Added Files
根据大多数主流印刷风格，`self`和`check`都是实词，请把`Check`的首字母也大写吧

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +# Data related API description
请注意标题中单词的首字母大写。

请同步检查并修改PR中的其它部分。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +### Change Detection Dataset`CDDataset`
`CDDataset`也是一个独立的单词，在`Dataset`之后请空一格。

请同步检查并修改PR中的其它部分。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`transforms`|`paddlers.transforms.Compose`|Data transformation operator applied to input data.||
`operator` -> `operators`
请同步修改PR中的其它位置。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`data_dir`|`str`|Dataset storage directory.||
`Directory that stores the dataset.`
请同步修改PR中其它位置。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`file_list`|`str`|File list path. File list is a text file, in which each line contains the path infomation of sample. The specific requirements of `CDDataset` on the file list are listed below.||
`of sample` -> `of one sample`
请同步修改PR中其它位置。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`num_workers`|`int` \| `str`|The number of auxiliary processes used when loading data. If it is set to `'auto'`, the following rules determine the number of processes to use:When the number of CPU c
`the following rules determine the number of processes to use` -> `use the following rules to determine the number of processes to use`；
冒号之后需要空一格：`use: When`；
分号之后不需要大写；
`use CPU cores to count half as many auxiliary processes` -> `the number of auxiliary processes is set to half the counts of CPU cores`

请同步修改PR中的其它位置。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`binarize_labels`|`bool`|If it is `True`, the change labels (and segmentation label) is binarized after all data transformation operators except `Arrange` are processed. For example, binarize a tag
If it is `True`, the change labels (and the segmentation labels) are binarized after all data transformation operators except `Arrange` are applied. For example, binarize labels valued in {0, 255} to {0, 1}.

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +- If `with_seg_labels` is `True`, each line in the file list should contain five space-separated items, the first three of which have the same meaning as `with_seg_labels` is `False`, and the last tw
and the last two represent the path of the segmentation labels for the first and second phase images (also in relative paths).

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +- If `with_seg_labels` is `False`, each line in the file list should contain three space-separated items representing, in turn, the path to `data_dir` for the first phase image, `data_dir` for the se
If `with_seg_labels` is `False`, each line in the file list should contain three space-separated items representing, in turn, the path to the image of the first temporal phase, path to the image of the second temporal phase, and the path to the change label. Each given path should be the path relative to `data_dir`.

请同步检查并更新PR中的其它位置。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`empty_ratio`|`float`|Negative sample ratio, take effect only if `allow_empty` is `True`. If `empty_ratio` is negative or greater than or equal to 1, all negative samples generated are retained.|`1.
`ratio. Take effect`

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +The requirments of `VOCDetDataset` for the file list are as follows:
`requirments`拼写错误。

请同步检查并修改PR中其它位置。

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`sr_factor`|`int` \| `None`|For super resolution reconstruction task, specify as super resolution multiple; For other tasks, specify as `None`.|`None`|
For super resolution reconstruction tasks, this is the scaling factor. For other tasks, please specify `sr_factor` as `None`.

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +According to the actual demand, the user can choose `paddlers.transforms.decode_image()` or `paddlers.transforms.DecodeImg` to read data. `DecodeImg` is one of[Data transformation operators](#Data tr
`According to the actual demand` -> `Depending on the practical demands`

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +According to the actual demand, the user can choose `paddlers.transforms.decode_image()` or `paddlers.transforms.DecodeImg` to read data. `DecodeImg` is one of[Data transformation operators](#Data tr
`of` 和 `Data transformation operators`之间缺少空格

2023-03-24 07:14 UTC, Bobholamovic commented on docs/apis/data_en.md
> +The argument lish of `decode_image()` function is as follows:
typo：`lish`

2023-03-24 07:49 UTC, lizechng commented
- https://github.com/PaddlePaddle/PaddleRS/pull/113#pullrequestreview-1356064407

已按照上述意见修改~

2023-03-24 08:41 UTC, Bobholamovic requested changes
发现先前轮次已接受的review意见并未完全得到落实。例如，

> 标题每个实词的首字母需要大写。

> 分号后面的单词首字母无需大写。

保证PR质量是最重要的，因此，**请确认对先前轮次的review意见已经完全修改完毕后再请求review**，否则我们可能会花费更多时间。为避免遗漏，后续将在先前review意见均已收到回复或完全得到落实的前提下继续给出新的review意见，感谢理解~

2023-03-24 08:41 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +2. Define a Test class for the new Model that inherits from `Test{task name}Model` and sets its `MODEL_CLASS` property to the new model, following the example already in the file.
此处尚未修改或回复

2023-03-24 08:41 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +## Contribution an Example
`Contribution` -> `Contribute`

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +`ClasDataset` is define in: https://github.com/PaddlePaddle/PaddleRS/blob/develop/paddlers/datasets/clas_dataset.py
typo: `defined`
请同步检查并修改PR中其它位置。

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +- If `read_geo_info` is `True`, a binary group is returned, in which the first element is the image data read, the second element is a dictionary, in which the key-value pair is the geographic inform
`binary group` -> `two-tuple`

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`use_stretch`|`bool`|Whether to stretch the image brightness by 2% linear. Take effect only if `to_uint8` is `True`.|`False`|
Whether to apply a linear stretch to image brightness (with 2% max and min values removed).

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +- If `read_geo_info` is `True`, a binary group is returned, in which the first element is the image data read, the second element is a dictionary, in which the key-value pair is the geographic inform
要不拆成两句写吧，这里从句有点儿套太多层了。

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +The `__call__` method of the `Transform` object takes a unique argument `sample`. `sample` must be a dictionary or a sequence of dictionaries. When `sample` is a sequence, perform data transformation
分号后有大写字母的问题尚未完全解决。建议通过正则表达式全局搜索、替换

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +The `__call__` method of the `Transform` object takes a unique argument `sample`. `sample` must be a dictionary or a sequence of dictionaries. When `sample` is a sequence, perform data transformation
key names -> keys

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +The `__call__` method of the `Transform` object takes a unique argument `sample`. `sample` must be a dictionary or a sequence of dictionaries. When `sample` is a sequence, perform data transformation
It should be noted that many of the `Transform` objects in PaddleRS overwrite key-value pairs, that is, there is an intersection between the input key and the output key. -> ``

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`'mask'`|Truth label path or data in image segmentation/change detection task.|
Ground-truth label
『真值』的统一表达为『ground-truth』，请同步检查并修改PR中其它位置。

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +    # Normalized data to [-1,1]
无需过去式

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +Generally, in the list of `Compose` object accepted data transform operators, the first element is `paddlers.Transforms.DecodeImg` object, used to read image data; The last element is [`Arrange` Oper
in the list of `Compose` object accepted data transform operators -> in the list of data transform operators accepted by a `Compose` object

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +For the verification set of image segmentation task and change detection task, the `ReloadMask` operator can be inserted before the `Arrange` operator to reload the GT label. The following is an exam
『验证集』的翻译为『validation dataset』
请同步检查并修改PR中其它位置

2023-03-24 08:41 UTC, Bobholamovic commented on docs/apis/data_en.md
> +For the verification set of image segmentation task and change detection task, the `ReloadMask` operator can be inserted before the `Arrange` operator to reload the GT label. The following is an exam
另外之前好像没有出现过`GT`的全称

2023-03-24 08:41 UTC, Bobholamovic commented on docs/data/dataset_summary_en.md
表格标题的大小写风格不统一，如：link是实词，也需要首字母大写

2023-03-24 09:56 UTC, lizechng commented on docs/CONTRIBUTING_en.md
> +2. Define a Test class for the new Model that inherits from `Test{task name}Model` and sets its `MODEL_CLASS` property to the new model, following the example already in the file.
- 在提交的修改中，Model已经更正为首字母小写。此条不清楚为何没有标记为`Outdated`
- 我会再检查一遍每个文件中标题实体单词的大小写问题和分号后单词的大小写问题。

下一轮次的提交中我会list每条意见的修改情况，辛苦您的审阅~

2023-03-25 08:52 UTC, lizechng commented
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1147241776 该意见已在上轮提交中进行修改
- 关于这里 https://github.com/PaddlePaddle/PaddleRS/pull/113#pullrequestreview-1356184354 提到的：
    - `标题每个实词的首字母需要大写`: 已完成检查
    - `分号后面的单词首字母无需大写`: 已通过正则搜索替换
- 本轮意见完成修改

感谢您的审阅~

2023-03-25 10:13 UTC, Bobholamovic requested changes
请根据review意见修改或回复意见。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/CONTRIBUTING_en.md
> +2. Define a Test class for the new Model that inherits from `Test{task name}Model` and sets its `MODEL_CLASS` property to the new model, following the example already in the file.
![image](https://user-images.githubusercontent.com/21275753/227708038-4ace5a58-c9f8-4009-90f7-7ef6e87061fd.png)
这句话里的`T`和`M`需要小写哈

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +If the download dependence is slow or times out when using `python setup.py install`, you can create `setup.cfg` in the same directory as `setup.py` and input the following content, then the download
`the download dependence` -> `the downloading of dependencies`

`and input the following content` -> `with the following content`

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +PaddleRS supports reading of various types of satellite data. To fully use PaddleRS remote sensing data reading function, you need to install GDAL as follows:
`To fully use PaddleRS remote sensing data reading function` -> `To use the full data reading functionality of PaddleRS`

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +Windows users can download the Python and system version corresponding to the .whl format installation package from [this](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal) to local, take *GDAL‑3.3.3
Windows users can download GDAL wheels from [this site](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal). Please choose the wheel according to the Python version and the platform. Take *GDAL‑3.3.3‑cp39‑cp39‑win_amd64.whl* as an example, run the following command to install:

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +- (Optional) Build from scratch. Multiple base images for PaddlePaddle can be selected by setting `PPTAG` to build cpus or different GPU environments:
`Select the base image for PaddlePaddle by setting `PPTAG`. You can build the image in a CPU-only environment or in GPU environments`

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +docker iamges  # View the ID of an image
这里有个typo。也请同步修复一下中文文档。

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +2. Start image
中文文档此处有误，应该为『启动容器』。请帮忙修复一下~
此处对应翻译为：`Start a container`

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> ++ After PaddleRS is installed, run the following command to perform single-card training. The script will automatically download the training data. Take DeepLab V3+ image segmentation model as an exa
`command` -> `commands`
`perform single-card training` -> `launch training with a single GPU`

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> ++ If multiple Gpus are required for training, for example, two graphics cards, run the following command:
请将Gpu统一写为`GPU`。

请同步检查并修改PR中的其它位置。

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +Set the `use_vdl` parameter passed to the `train()` method to `True`, then the training log will be automatically stored in the format of `save_dir` (user specified path) in the subdirectory named `v
1. `parameter` -> `argument`
2. `then`无法作为连词，因此使用`and then`
3. 此段首句翻译后意思改变，疑似机翻，请进行人工检查
4. `visual indicators` -> `the indicators and metrics`
5. `DeepLab V3+ model is also taken as an example` -> `We also take DeepLab V3+ as an example`

2023-03-25 10:13 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +Once the service is started, use your browser to open https://0.0.0.0:8001 or https://localhost:8001 to access the visual page.
`use your browser to open https://0.0.0.0:8001 or https://localhost:8001 to access the visual page.` -> `open https://0.0.0.0:8001 or https://localhost:8001 in your browser to access the VisualDL page.`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/intro/transforms_en.md
> +In the actual model training process, it is often necessary to combine a variety of data preprocessing and data augmentation strategies. PaddleRS provides `paddlers.transforms.Compose` operator to ea
PaddleRS provides `paddlers.transforms.Compose` operator to easily combine multiple data transformation, enables the operator to serial execution.  此句存在语法错误，请修正。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/intro/transforms_en.md
> +## List of PaddleRS Supported Data Conversion Operators
`数据变换`应统一翻译为`Data Transformation`，`Data Conversion`疑似机翻，请同步检查并修改PR中的其它位置。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/intro/transforms_en.md
> +PaddleRS organically integrated data preprocessing/data augmentation (collectively called data transformation) strategies required by different remote sensing tasks, and designed a unified operator.
此段首句为何使用过去式陈述？

2023-03-25 10:13 UTC, Bobholamovic commented on docs/intro/transforms_en.md
> +| AppendIndex          | The remote sensing index is calculated and added to the input image. | All tasks  | ... |
`Purpose`一栏中的句子请修改为祈使句。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/intro/model_zoo_en.md
> +All PaddleRS currently supported models are as follows (those marked \* are dedicated models for remote sensing) :
`All models currently supported by PaddleRS`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/intro/indices_en.md
> +|    Band name    |     Description    | Reference wavelength range(μm) |  \*Reference wavelength source  |
请对照PaddleRS develop分支目前最新文档更新此文档内容。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/intro/data_prep_en.md
> +| Task | Dataset Name | Dataset Urls | Preprocessing Script |
`URL`三个字母都需要大写。请同步检查并修改PR中的其它位置。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/intro/data_prep_en.md
> +# Dataset Preprocessing Script
`Script`为可数名词，此处需使用复数形式。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +- Pay attention to capitalizing the first letter and punctuation (especially period **.**) in accordance with English grammar rules.
`capitalizing the first letter and punctuation (especially period **.**) in accordance with English grammar rules` -> `capitalization and punctuation rules in accordance with English grammar`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +- For the **input parameter name**, **the property or method of the input parameter**, and the **file path** that appear in the comment, surround it with `\`.
应该是使用反引号包围。这里中文文档也写错了，只需要打单个反引号就行（中文文档打了三个），麻烦同步修改一下。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +- Line breaks and indentation are required between each module's title/subtitle and the concrete content, and **1** blank lines are inserted between the `Examples:` title and the sample code content.
`are inserted` -> `should be inserted`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +Requirement: The user copies the sample code to the script to run. Note the need to add the necessary `import`.
这句疑似机翻，请润色一下~

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +- When using the description of `list[{type name}]` and `tuple[{type name}]`, the default assumption is that the list or tuple parameters are homogeneous (that is, all elements contained in them have
`contained in them` -> `contained in the list or tuple`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +- Separated type if it is a simple type such as `int`, `Tensor` etc, then `|` don't need to add a space before and after, if it is a more complex types such as `list[int]` and `tuple[float]` requires
这句疑似机翻，请润色一下

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +- For parameters that have a default value, at least explain the logic of taking the default value, not just what the parameter is and what the default value is.
`For parameters that have a default value, please explain why we use that default value, not just what the parameter is and what the default value is.`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +## 2 Complete docstring Example
`docstring` -> `Docstring`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +# PaddleRS Code Annotation Specification
PaddleRS Specification for Code Annotation

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +## 1 Annotation Specification
Specification for Docstrings

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +### 1.1 Function/Class Function Description
Description on Functionality of Function/Class

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +- [Add Remote Sensing Special Model](#1-Add Remote Sensing Special Model)
请确认此文档中的markdown anchor符合GitHub markdown规则，且在渲染后能够正常工作。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +- [Add Data Preprocessing Data Augmentation Function or Operator](#2-Add Data Preprocessing Data Augmentation Function or Operator)
这里原始的中文文档在『数据预处理』和『数据增强』之间缺少『或』字，辛苦补充一下并对应修改此文档。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +### 1.1 Edit Model Definitions
`Edit` -> `Write`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +Create a new file in the subdirectory named `{model name lowercase}.py`.  Write the complete model definition in the file.
`named` -> `and name it`
以消除歧义

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +The new model must be a subclass of `paddle.nn.Layer`. For the tasks of image segmentation, object detection, scene classification and image restoration, relevant specifications formulated in Kit [Pa
`Kit` -> `development kits`

请不要在句中随意进行首字母大写。

此外，`parameter`一般指『形参』，`argument`指『实参』，而这段话里出现的『参数』几乎都是指实参，请注意区别。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +- The `forward()` method accepts three input parameters, namely `self`, `t1` and `t2`, where `t1` and `t2` represent the input image of the first and last two phases respectively.
`and last` -> `and second`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +- For a multi-task change detection model (for example, the model outputs both change detection results and building extraction results of two phases), the class `USE_MULTITASK_DECODER` attribute nee
the class `USE_MULTITASK_DECODER` attribute -> the class attribute `USE_MULTITASK_DECODER`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +Note that if a common component exists in a subdirectory, For example, contents in `paddlers/rs_models/cd/layers`, `paddlers/rs_models/cd/backbones` and `paddlers/rs_models/seg/layers` should be reus
逗号之后请勿大写。
另外此处`subdirectory`之后应该用句号。
请同步检查并修改PR中的其他部分。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/data_en.md
> +|`'mask'`|Ground-Truth label path or data in image segmentation/change detection task.|
此处`T`无需大写，句首字母大写规则与标题不同。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/data_en.md
> +For the validation dataset of image segmentation task and change detection task, the `ReloadMask` operator can be inserted before the `Arrange` operator to reload the Ground-Truth label. The followin
正文句中的`Ground-Truth`无需大写。请同步检查并修改PR中的其它位置。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +Interface format:
`Interfact format`可修改为`Interface`（因为英语中的`interface`本身就有这个含义）

请同步检查并修改PR中的其它位置。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`transforms`|`paddlers.transforms.Compose` \| `None`|Apply data transformation operator to input data. If `None`, the data transformation operator of trainer in the validation phase is used.|`None`|
`transformation operators`（句中有2处）
请同步检查并修改PR中的其它部分。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +Considering the large format property of remote sensing image, PaddleRS provides sliding window inference support for some tasks. PaddleRS 'sliding window inference features the following:
1. `large format property`疑似机翻，请修改。
2. `PaddleRS 'sliding window inference` 是否要表示`The sliding window inference of PaddleRS`？

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +1. In order to solve the problem of insufficient memory caused by reading the whole large image at once, PaddleRS adopted the lazy loading memory technology, which only read and processed the image b
请说明使用一般过去式时态的原因。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +2. Users can customize the size and step of the slide window. Supports sliding window overlap. PaddleRS will automatically merge model prediction results for the overlapped parts between Windows.
此段疑似机翻，请人工润色。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +3. The inference results can be saved in GeoTiff format, and the reading and writing of geographic transformation information and geographic projection information can be supported.
`can be supported` -> `is supported`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`merge_strategy`|`str`|Strategies used to merge sliding window overlapping areas.`'keep_first'` represents the prediction category that retains the most advanced window in the traversal order (left
`intensive reasoning`和`window interface`疑似机翻和typo，请检查此PR中其它位置是否存在此问题并同步修改。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`block_size`|`list[int]` \| `tuple[int]` \| `int`|The size of the slide window (specifying the width, height in a list or tuple, or the same width and height in an integer).||
请将所有`slide window`统一为`sliding window`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`overlap`|`list[int]` \| `tuple[int]` \| `int`|The slide step size of the slide window (specifying the width, height in a list or tuple, or the same width and height in an integer).|`36`|
`slide step size` -> `sliding step size`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`transforms`|`paddlers.transforms.Compose` \| `None`|Apply data transformation operator to input data. If `None`, the data transformation operator of trainer in the validation phase is used.|`None`|
`operators`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`save_dir`|`str`|Predict results output path.||
`Predict` -> `Prediction`或`Predicted`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`cpu_thread_num`|`int`|The number of threads when inference is performed using the CPU.|`1`|
`the CPU` -> `CPUs`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`img_file`|`list[str\|tuple\|np.ndarray]` \| `str` \| `tuple` \| `np.ndarray`|For scene classification, object detection, image restoration and image segmentation tasks, this parameter can be a sing
`binary group` -> `two-tuple`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`transforms`|`paddlers.transforms.Compose`\|`None`|Apply data transformation operator to input data. If `None`, the operators read from 'model.yml' is used.|`None`|
`operator`加复数。

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +Realize the sliding window inference function. It is used in the same way as `BaseSegmenter` and `slider_predict()` of `BaseChangeDetector`.
`Realize` -> `Implements`

2023-03-25 10:13 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`block_size`|`list[int]` \| `tuple[int]` \| `int`|The size of the slide window (specifying the width, height in a list or tuple, or the same width and height in an integer).||
各个文档中表格里的description，有的时候省略句首的定冠词，有的时候没有。请统一一下风格吧

2023-03-27 06:36 UTC, lizechng commented
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1148338740 中的时态问题，翻译时是想使用完成时，`PaddleRS organically integrated`->`PaddleRS has organically integrated`.  或者应修改为`PaddleRS organically integrates`? （同样的问题还有 https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1148338740 ）
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1148338981 已按照develop分支最新文档更新
- 其余意见已经修改

2023-03-27 06:43 UTC, Bobholamovic commented
> * [【Hackathon No.153】PaddleRS 英文文档 #113 (comment)](https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1148338740) 中的时态问题，翻译时是想使用完成时，`PaddleRS organically integrated`->`PaddleRS has organically integrated`.  或者应修改为`PaddleRS organically integrates`? （同样的问题还有 [【Hackathon No.153】PaddleRS 英文文档 #113 (comment)](https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1148338740) ）
> * [【Hackathon No.153】PaddleRS 英文文档 #113 (comment)](https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1148338981) 已按照develop分支最新文档更新
> * 其余意见已经修改

1. 嗯嗯，这样的话这两处可以改成完成时~

2023-03-27 08:39 UTC, Bobholamovic requested changes
发现先前轮次已接受的review意见并未完全得到落实。请在完成修改后再request review~

2023-03-27 08:39 UTC, Bobholamovic commented on tutorials/train/README_en.md
> +The PaddleRS code will be updated as the development progresses. You can install code for the develop branch to use the latest features as follows:
`install code for the develop branch` -> `install the develop branch`

2023-03-27 08:39 UTC, Bobholamovic commented on docs/apis/train_en.md
> +### Initialize `BaseChangeDetector` Sub-Class Object
`Sub-Class`中间建议不添加连字符（添加连字符的写法很少见），写为`Subclass`。请同步检查并修改PR中的其它位置。

2023-03-27 08:39 UTC, Bobholamovic commented on docs/apis/train_en.md
> +**Trainer** encapsulates model training, validation, quantization, and dynamic graph inference, defined in files of `paddlers/tasks/` directory. For user convenience, PaddleRS provides trainer that i
`provides trainer` -> `provides trainers`

2023-03-27 08:39 UTC, Bobholamovic commented on docs/apis/train_en.md
> +- Different sub-classes support model-related input parameters, for details, refer to [Model definition](https://github.com/PaddlePaddle/PaddleRS/blob/develop/paddlers/rs_models/cd) and [Trainer defi
`refer to [model definitions](https://github.com/PaddlePaddle/PaddleRS/blob/develop/paddlers/rs_models/cd) and [trainer definitions](https://github.com/PaddlePaddle/PaddleRS/blob/develop/paddlers/tasks/change_detector.py)`

2023-03-27 08:39 UTC, Bobholamovic commented on docs/apis/train_en.md
> +- Generally, the `num_classes` and `backbone` parameters can be set to indicate the number of output categories of the model and the type of backbone network used respectively. Compared with other ta
`respectively`之前需要加逗号

2023-03-27 08:39 UTC, Bobholamovic commented on docs/apis/train_en.md
> +- Different sub-classes support model-related input parameters, for details, refer to [Model definition](https://github.com/PaddlePaddle/PaddleRS/blob/develop/paddlers/rs_models/det) and [Trainer def
这里需要拆成两句话写，或者使用从句，要不然有语法错误（一个句子无连词两个谓语）。
请同步检查并修改PR中的其它位置。

2023-03-27 08:39 UTC, Bobholamovic commented on docs/apis/train_en.md
> +- Generally support setting `sr_factor` parameter, representing super resolution multiple; for models that do not support super resolution rebuild tasks, `sr_factor` is set to `None`.
`super resolution multiple` -> `the scaling factor in image super resolution`

2023-03-27 13:22 UTC, lizechng commented
> 发现先前轮次已接受的review意见并未完全得到落实，如：
> 
> > 各个文档中表格里的description，有的时候省略句首的定冠词，有的时候没有。
> 
> 请在完成修改后再request review~

- 文档中表格里的description已统一为省略句首的定冠词
- 其他意见已修改~

2023-03-28 03:08 UTC, Bobholamovic requested changes
留了一些意见

2023-03-28 03:08 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +### 1.3 Edit Trainer
`Write Trainer Definitions`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +It should be noted that for the image restoration task, the forward and reverse logic of the model are implemented in the trainer definition. For GAN and other models that need to use multiple networ
`reverse` -> `backward`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +- Rewrite `train_step()` method to write the specific logic of one iteration during model training. The usual approach is to call `run_gan()` over and over again, constructing different `inputs` to w
`over and over again` -> `multiple times`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +Define new operators in `paddlers/transforms/operators.py`, all operators are inherited from `paddlers.transforms.Transform`. The operator's `apply()` method receives a dictionary `sample` as input,
`are inherited from` -> `inherit from`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +After writing the implementation of the operator, **must write docstring and add the class name in `__all__`.**
`must`前面加`you`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +If processing logic is more complicated, it is recommended that the encapsulated in the first function, added to the `paddlers/transforms/functions.py`, then call the function in the `apply*()` of op
If the operator has a complicated implementation, it is recommended to define functions in `paddlers/transforms/functions.py` and call them in `apply*()` of operators.

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `coco2mask.py`: Convert COCO annotated files to.png.
`Convert COCO annotation files to .png files`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `match.py`: Realize the registration of two images.
`Register two images`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `split.py`: Slice large format image data.
Slice a large image.

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `extract_ms_patches.py`: Extract multi-scale image blocks from the whole remote sensing image.
`the whole` -> `a`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/dataset_summary_en.md
本文件中存在一些未翻译的文本，请问是刻意留下的嘛？

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/dataset_en.md
> +* Sample data of typical urban roads in China of 2020(CHN6-CUG), Provided by Professor [Qiqi Zhu](http://grzy.cug.edu.cn/zhuqiqi), China University of Geosciences. Please refer to [here](http://grzy.
`Provided`的`P`不用大写

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/dataset_en.md
> +PaddleRS collected and summarized the most commonly used **open source** deep learning data sets in the field of remote sensing, providing the following information for each data set: dataset descrip
请改为完成时或一般现在时。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/apis/data_en.md
> +The argument list of `decode_image()` function is as follows:
现在出现了`parameter list`和`argument list`混用的情况，请检查并统一PR各文件中的表述（现在`parameter list`居多，建议用`parameter list`代替`argument list`）。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +|`model_dir`|`str`|Model path (must be an exported deployed or quantified model).||
『量化』正确术语：`quantified` -> `quantized`
请同步检查并修改PR中的其它部分。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +The main function of `coco2mask.py` is to convert images and corresponding COCO format split tags into images and .png format tags, and the results will be stored in `img` and `gt`  directories respe
这段翻译有很大错误，请人工检查。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `save_path`：path to save shapefile, default is `output`.
不要把两个独立句子用逗号连在一起。此外，句首字母大写。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `ignore_index`：index values that need to be ignored in shapefile (such as background classes in split tasks) default to `255`.
句首字母大写。请同步检查并修改PR中的其它位置。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `ignore_index`：index values that need to be ignored in shapefile (such as background classes in split tasks) default to `255`.
这里应该不用复数，只能指定一个数值。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
> +The main function of `geojson2mask.py` is to convert the geoJson-formatted tag to a .tif raster format. The usage is as follows:
`geoJson` -> `GeoJSON`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/tools_en.md
这个文档中包含了很多机翻内容，请人工检查并润色。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +Remote sensing technology has the characteristics of macro, multi-band, periodicity and economy. Macro refers to that the higher the remote sensing platform is, the wider the perspective will be, and
前后不统一：`economy` vs `economic`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +![图片3](../images/band_combination.jpg)
可以替换一下中文。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/coco_tools_en.md
> +coco_tools is a set of tools provided by PaddleRS for handling COCO annotated files. It is located in the `tools/coco_tools/` directory. Because [pycocotools library] (https://pypi.org/project/pycoco
`COCO annotated files` -> `COCO annotation files`

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/coco_tools_en.md
> +- The `info` key is a dictionary, there are 6 key-value pairs, the output shows the first 5 pairs;
这里的表述好像有些歧义，`key`本身应该不是字典，应该是`key`对应的值为字典。可以考虑改成：
`info`: A dictionary. There are...
这样的格式。

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/coco_tools_en.md
> +| `--png_shapeRate_path` | (Optional) png Image saving path. The image content is a one-dimensional distribution of shape ratio (width/height) of all target detection boxes.| `None`        |
句中不要随意进行首字母大写

2023-03-28 03:08 UTC, Bobholamovic commented on docs/data/coco_tools_en.md
> +After the preceding command is executed, the following information is displayed:
这里是不是该用一般将来时？

2023-03-30 08:51 UTC, lizechng commented
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1149964457 这些未翻译的文本是之前的疏漏了。已更正。
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1149972468 tool_en.md 已经重新翻译
- 其余意见已修改

2023-03-30 09:56 UTC, Bobholamovic requested changes
留了一些意见。另外发现PR中仍存在句中无需大写的单词首字母大写的情况，请着重检查并修改。

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +Remote sensing technology has the characteristics of macro, multi-band, periodicity and economic. Macro refers to that the higher the remote sensing platform is, the wider the perspective will be, an
`Remote sensing technology has the characteristics of macroscopic, multi-band, periodic and economic`
`Macro` -> `Macroscoptic`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/coco_tools_en.md
> +- `info`: A dictionary. There are 6 key-value pairs, the output shows the first 5 pairs;
`the output` 前加`and`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/coco_tools_en.md
> +- `images`: A list with 5000 elements, and the output shows the first 5;
`first 5` -> `first five`
与其他句子统一~

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +Raster formats are ideal for analysis that looks at spatial and temporal changes because each data value has a grid-based accessible location. This allows us to access the same geographic location in
`looks at` -> `concentrates on`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +When the Earth observation satellite takes a picture, the sensor will record the DN value (Digital Number) of different wavelength electromagnetic wave in the grid pixel. Through DN value, the irradi
Digital Number 是DN的缩写，所以这个括号应该在DN之后。
另外英文中时候number已有value之意，所以直接说DN就可以，不必写DN value。

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +When the Earth observation satellite takes a picture, the sensor will record the DN value (Digital Number) of different wavelength electromagnetic wave in the grid pixel. Through DN value, the irradi
`irradiance rate` 去掉rate

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +When the Earth observation satellite takes a picture, the sensor will record the DN value (Digital Number) of different wavelength electromagnetic wave in the grid pixel. Through DN value, the irradi
`Earth`统一首字母不大写吧，这段后续提到的时候也没有大写

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +When the Earth observation satellite takes a picture, the sensor will record the DN value (Digital Number) of different wavelength electromagnetic wave in the grid pixel. Through DN value, the irradi
`solar zenith Angle`
请不要在句中随意进行首字母大写，因为大写有强调的含义。

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +Electromagnetic spectrum is the result of human beings according to the order of wave length or frequency, wave number, energy, etc. The human eye perceives only a small range of wavelengths in the e
句首缺少定冠词，`The electromagnetic spectrum`。

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +Since most of the current CV task processing processes are designed based on natural images, remote sensing data sets of RGB type are widely used in CV field.
`Since the data processing pipelines of most CV tasks are designed based on natural images`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +MSI (Multispectral Image) and HSI (Hyperspectral Image) usually consist of several to hundreds of bands, The two are distinguished by different spectral resolution (*spectral resolution refers to the
`of bands,` -> `of bands.`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +MSI (Multispectral Image) and HSI (Hyperspectral Image) usually consist of several to hundreds of bands, The two are distinguished by different spectral resolution (*spectral resolution refers to the
`Compared with HSI, MSI has less band number, wider band and higher spatial resolution. However, HSI has more bands, narrower bands and higher spectral resolution.`
->
`MSI has fewer bands, wider band, and higher spatial resolution, while HSI has more bands, narrower bands, and higher spectral resolution.`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +The difference between RGBD image and RGB image is that there is an extra D channel, namely depth. Depth images are similar to grayscale images, except that each pixel value represents the actual dis
`The difference between RGBD images and RGB images is that there is an extra D channel in RGBD images, namely the depth.`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +7. **Defined Projection**: Define projection information (a geographic coordinate system) on the data.
为什么是过去分词`Defined`？

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +Compared with natural images, the preprocessing of remote sensing images is very complicated. Specifically, it can be divided into the following steps:
`very complicated` -> `rather complicated`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/rs_data_en.md
> +- [Principles and Applications of Remote Sensing by Sun Jia-liu.](https://book.douban.com/subject/3826668/)
这里是否需要句号？

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `extract_ms_patches.py`: Extracts multi-scale image blocks from entire remote sensing images.
前面都是祈使句，要不这里也用祈使句吧~ 请去掉`Extracts`的`s`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +The main function of `mask2shape.py` is to convert the segmentation results in .png format into shapefile format (vector image). The usage is as follows:
矢量图是`vector graphics`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +python mask2shape.py --srcimg_path {path to the original image with geographic information.} --mask_path {input segmentation label path} [--save_path {output vector image path}] [--ignore_index {inde
`geographic information.` 就不用加句号了吧
请同步检查并修改PR中的其它位置。

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +The main function of `geojson2mask.py` is to convert the geoJson-formatted labels to a .tif raster format. The usage is as follows:
`geoJson`->`GeoJSON`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `im1_path`: The file path of the first temporal image. This image must contain geospatial information and will be used as the reference image during the registration process.
请统一一下句首的定冠词是否保留

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `im1_bands`: The bands of the first temporal image used for registration, specified as three channels (representing R, G, and B) or a single channel. Default is [1, 2, 3].
这里的`[1, 2, 3]`好像忘记用反引号圈起来了，也辛苦一并修改一下中文文档吧~

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `mask_path`: Path of the label image to be split together, default is `None`.
`, default is` -> `Default is`
请同步检查并修改PR中的其它位置。

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `block_size`: Size of the split image blocks, default is 512.
这里的`512`好像忘记用反引号圈起来了，也辛苦一并修改一下中文文档吧~

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `save_dir`: folder path to save the split results, default is `output`.
首字母需要大写。另外，`Folder path` -> `Directory`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `--visualize`: If specified, after the program is executed, the image `./vis_quadtree.png` will be generated, which contains the visualization result of the node situation in the quadtree. An examp
`contains the visualization result of the node situation` -> `visualizes the nodes`

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `im_paths`: Path of the source image(s), can specify multiple paths.
这句有语病，请修改一下

2023-03-30 09:56 UTC, Bobholamovic commented on docs/data/tools_en.md
> +- `mask_path`: Path to the Ground-truth label.
句中`G`不用大写，请同步检查并修改PR中的其它位置。

2023-03-30 12:22 UTC, lizechng commented
- https://github.com/PaddlePaddle/PaddleRS/pull/113#discussion_r1153012528 已统一为不保留定冠词。
- https://github.com/PaddlePaddle/PaddleRS/pull/113#pullrequestreview-1364597729 对于句中的单词首字母大写的问题已经通过正则匹配进行修正，匹配规则是`(?-i)\b[a-z]\w*\b (?-i)\b[A-Z]\w*\b`,即`[小写单词][空格][首字母大写单词]`。此外，对于`Github` `Transformer`以及模型名如`Deeplab`等是否需要首字母大写（目前这些情况仍旧是保留了大写）？
- 其他意见已修改

2023-03-30 12:29 UTC, Bobholamovic requested changes
剩余一些小意见~

2023-03-30 12:29 UTC, Bobholamovic commented on docs/apis/data_en.md
> +The `__call__` method of the `Transform` object takes a unique argument `sample`. `sample` must be a dictionary or a sequence of dictionaries. When `sample` is a sequence, perform data transformation
`python`的首字母`P`需要大写

2023-03-30 12:29 UTC, Bobholamovic commented on docs/apis/infer_en.md
> +Currently, the image segmentation trainer ([`BaseSegmenter`](https://github.com/PaddlePaddle/PaddleRS/blob/develop/paddlers/tasks/segmenter.py) and subclasses) and change detection trainer ([`BaseCha
`api`三个字母需要大写`API`

2023-03-30 12:29 UTC, Bobholamovic commented on docs/data/dataset_en.md
> +PaddleRS has collected and summarized the most commonly used **open source** deep learning data sets in the field of remote sensing, providing the following information for each data set: dataset des
aistudio的正式写法为AI Studio

2023-03-30 12:29 UTC, Bobholamovic commented on docs/data/dataset_en.md
> +* Sample data of typical urban roads in China of 2020(CHN6-CUG), provided by professor [Qiqi Zhu](http://grzy.cug.edu.cn/zhuqiqi), China University of Geosciences. Please refer to [here](http://grzy.
根据英语语法，此处`professor`需要首字母大写

2023-03-30 12:29 UTC, Bobholamovic commented on docs/data/tools_en.md
> +The main function of `geojson2mask.py` is to convert the GeoJson-formatted labels to a .tif raster format. The usage is as follows:
`GeoJson` -> `GeoJSON`

2023-03-30 12:29 UTC, Bobholamovic commented on docs/dev/dev_guide_en.md
> +When writing the script, use the python standard library `argparse` to process the command-line arguments entered by the user and execute the specific logic in the `if __name__ == '__main__':` code b
同上

2023-03-30 12:29 UTC, Bobholamovic commented on docs/dev/docstring_en.md
> +        # Use it as a python decorator.
同上

2023-03-30 12:55 UTC, lizechng commented
> 剩余一些小意见~

已修改~

2023-03-30 12:59 UTC, Bobholamovic approved these changes
LGTM.

2023-03-30 13:00 UTC, Bobholamovic commented
我们将在CI通过后合入此PR。

再次感谢你为PaddleRS贡献文档，以及对PR review工作的配合。

2023-03-30 13:08 UTC, merged