【Hackathon No.152】PaddleRS API 文档完善
PaddlePaddle/PaddleRS pull request #115
Opened 2023-03-21 07:01 UTC by ggggkkkknnnn

### PR types

Others

### PR changes

Docs
### Description

1. 撰写中英文文档，对 PaddleRS 每个模型的构造参数进行详细说明（参考 paddlers/rs_models 中的 docstring）
2  撰写中英文文档，对 PaddleRS 每个数据预处理/数据变换算子的构造参数进行详细说明
3. 完善 PaddleRS quick start 中英文文档，在已有的『模型训练』部分内容基础上，添加『模型精度验证』与『模型部署』部分内容。

2023-03-21 07:34 UTC, Bobholamovic requested changes
感谢你为PaddleRS贡献文档。对于这个PR，我有如下意见和建议：
1. 请不要在PR中包含`.idea`目录中的任何内容；
2. 『API文档』指的是文档（markdown、rst等格式），而不是doc string。而这个PR中为每个API添加了额外的中文doc string，这既不符合『撰写文档』的要求，也不符合Python语言规范。
3. 请注重翻译质量，修改如『罗德里戈·凯·达特等人。“用于变化检测的全卷积暹罗网络”』这样的『机翻』表述。另外，论文名称不需要翻译。
4. 请在充分了解PaddleRS模型部署能力后再为PaddleRS增加『模型部署』教程。

2023-03-21 07:53 UTC, ggggkkkknnnn commented
“撰写中英文文档，对 PaddleRS 每个模型的构造参数进行详细说明”对于这个我有一些疑问，题目的意思是我需要新建两个文档来对每个模型的构造参数进行描述吗。如果是这样的话我的两个文档又该在哪里创建

2023-03-21 08:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleRS?pullRequest=115) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleRS?pullRequest=115) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleRS?pullRequest=115) it.</sub>

2023-03-21 09:34 UTC, Bobholamovic commented
> “撰写中英文文档，对 PaddleRS 每个模型的构造参数进行详细说明”对于这个我有一些疑问，题目的意思是我需要新建两个文档来对每个模型的构造参数进行描述吗。如果是这样的话我的两个文档又该在哪里创建？有一些困惑，希望指点。

已在 https://github.com/PaddlePaddle/PaddleRS/issues/116 回复。另外，请签署CLA协议。

2023-03-22 03:03 UTC, ggggkkkknnnn commented
> 感谢你为PaddleRS贡献文档。对于这个PR，我有如下意见和建议：
> 
> 1. 请不要在PR中包含`.idea`目录中的任何内容；
> 2. 『API文档』指的是文档（markdown、rst等格式），而不是doc string。这个PR中为每个API添加了额外的中文注释，这既不符合『撰写文档』的要求，也不符合Python语言规范（只有函数/类定义起始处的第一个string才是doc string）。
> 3. 请注重翻译质量，修改如『罗德里戈·凯·达特等人。“用于变化检测的全卷积暹罗网络”』这样的『机翻』表述。另外，论文名称和作者的名字不需要翻译。
> 4. 请在充分了解PaddleRS模型部署能力后再为PaddleRS增加『模型部署』教程。

您好，已进行修改

2023-03-22 03:42 UTC, Bobholamovic requested changes
留了一些意见。

2023-03-22 03:42 UTC, Bobholamovic commented on .idea/.gitignore
请不要在PR中包含`.idea`目录。

2023-03-22 03:42 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +##BIT
类名、变量名用反引号包围。请参考https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/apis/train.md

请同步检查PR中的其它位置，并做修改。

2023-03-22 03:42 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +#PaddleRS中每个模型的构造参数
名称不够书面。

另外请在撰写文档前阅读PaddleRS文档并了解PaddleRS相关概念。例如，PaddleRS的`paddlers/tasks`中存放的（也是这篇文档中介绍如何构造的）数据集结构的官方中文称呼是『训练器』，而不是『模型』。参见：
https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/apis/train.md

此处为了避免用户混淆，我认为可以保留『模型构造参数』的说法，但需要额外说明一下，这篇文档中的『模型』指的实际是『训练器』而不是『网络实现』。

2023-03-22 03:42 UTC, Bobholamovic commented on paddlers/transforms/operators.py
为什么修改这个文件呀？

2023-03-22 03:42 UTC, Bobholamovic commented on paddlers/rs_models/clas/condensenetv2.py
> +
缺少参考文献

2023-03-22 03:42 UTC, Bobholamovic commented on paddlers/rs_models/clas/condensenetv2.py
> +        fc_channel (int): indicates the number of output channels of the full connection layer.
大小写不统一。句首字母请统一大写。

2023-03-22 12:49 UTC, ggggkkkknnnn commented on paddlers/rs_models/clas/condensenetv2.py
> +        fc_channel (int): indicates the number of output channels of the full connection layer.
已修改

2023-03-22 12:49 UTC, ggggkkkknnnn commented on paddlers/rs_models/clas/condensenetv2.py
> +
已添加参考文献

2023-03-22 12:50 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +#PaddleRS中每个模型的构造参数
已修改名称为“PaddleRS模型构造参数”，并对文档内容进行介绍

2023-03-22 12:50 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +##BIT
已修改，并修改PR中其他类似错误

2023-03-22 12:50 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +##BIT
已修改，并修改PR中其他类似错误

2023-03-22 12:50 UTC, ggggkkkknnnn commented on .idea/.gitignore
已删除PR中.idea目录

2023-03-23 02:29 UTC, Bobholamovic requested changes
请根据review意见继续修改~ 如果对review意见有疑问的话，可以直接在conversation中回复。

2023-03-23 02:29 UTC, Bobholamovic commented on .gitignore
> +.idea
这一个block全是安装相关的。建议把移到`.idea`放在
```
# myvscode
.vscode
```
之后，并添加相应注释
```
# myidea
.idea
```

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +本文档详细介绍了PaddleRS各个模型训练器的构造参数，包括其参数名，参数类型，参数描述及默认值。
这里的介绍不全。在[这里](https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/intro/model_zoo.md)可以找到PaddleRS支持的模型列表。

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +该模型的原始文章见于Yang L, Jiang H, Cai R, et al. Condensenet v2: Sparse feature reactivation for deep networks[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2021: 356
参考文献格式与其它文章不同

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +|`video_len (int，可选)`| 构造的伪视频的帧数             | `8`    |
有的地方`optional`被翻译为了`可选`，有的地方没有。请统一风格。

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +|`in_channels (int)`|输入图像的频带数|       |
`频带数`疑似机翻，是不是`波段数`？

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +|`ds_factor (int，可选)`|注意力模块的下采样因子。当' ds_factor '设置值大于1时，输入特征将首先经过内核大小为' ds_factor '的平均池化层处理，然后用于计算注意力得分。 | `1.`  |
' ds_factor ' -> \`ds_factor\`
请检查PR中提交的其它部分，同步修改类似情形。

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +|`num_classes (int)`| 目标类的唯一数量 |          |
这个看起来太机翻了……请检查PR中包含的所有文档内容，提升翻译质量。

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +|`fsr_out_channels (int，可选)`| F-S关系模块输出的通道数 | `256`      |
对于论文中提出的特殊模块名称，如果在不确定准确翻译的情况下，可以保留英文原名，或者在翻译的名字后面加括号注释英文原名。

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +| 数据变换算子名                | 用途                                                     | 任务     | ... |
这个列表是不是和已有文档中的内容重复了？如果是的话，建议给一个链接就可以，以免后续维护重复的样本

2023-03-23 02:29 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +对输入施加随机模糊
这里是不是格式不太对？漏写了一个反引号

2023-03-23 02:29 UTC, Bobholamovic commented on paddlers/rs_models/clas/condensenetv2.py
> +
参考文献格式与已有的其它模型不统一

2023-03-23 02:29 UTC, Bobholamovic commented on paddlers/rs_models/clas/condensenetv2.py
> +
这里只需要空一行。

2023-03-23 09:50 UTC, ggggkkkknnnn commented
针对提出的建议已全部进行修改，请review一下

2023-03-23 10:00 UTC, Bobholamovic requested changes
还是有一些基础问题，请修改~

2023-03-23 10:00 UTC, Bobholamovic commented on .gitignore
> +#myidea
`#`之后空一格

2023-03-23 10:00 UTC, Bobholamovic commented on .gitignore
> +
无需增加空行

2023-03-23 10:00 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +本文档详细介绍了PaddleRS各个模型训练器的构造参数，包括其参数名，参数类型，参数描述及默认值。
`参数名`、`参数类型`、`参数描述`用顿号（`、`）分隔

2023-03-23 10:00 UTC, Bobholamovic commented on docs/intro/model_cons_param_en.md
格式有问题：
![image](https://user-images.githubusercontent.com/21275753/227167834-72feb156-7802-43e7-af6a-53558e08c694.png)

请检查markdown语法。在编写完文档后请检查渲染结果是否符合预期。另外，请同步修改其它文档。

2023-03-23 10:00 UTC, Bobholamovic commented on tutorials/train/README.md
> +```shell
语言名称错误，应该是python

2023-03-23 10:00 UTC, Bobholamovic commented on tutorials/train/README.md
> +使用预测接口的基本流程为：首先构建Predictor对象，然后调用Predictor的predict()方法执行预测。需要说明的是，Predictor对象的predict()方法返回的结果与对应的训练器（在paddlers/tasks/目录的文件中定义）的predict()方法返回结果具有相同的格式。
`Predictor`、`predict()`、`paddlers/tasks/`等均未添加反引号。请同步检查PR中其它部分。

2023-03-23 10:00 UTC, Bobholamovic commented on paddlers/transforms/operators.py
为什么删除此模块？这将导致PaddleRS不可用。

2023-03-23 12:13 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_en.md
这个在我本地是可以渲染成功的。
![image](https://user-images.githubusercontent.com/90295025/227193839-3158d7f4-7cea-401b-a7e9-0e30e47ffa99.png)

2023-03-23 12:14 UTC, ggggkkkknnnn commented on .gitignore
> +
已修改

2023-03-23 12:14 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +本文档详细介绍了PaddleRS各个模型训练器的构造参数，包括其参数名，参数类型，参数描述及默认值。
已修改

2023-03-23 12:14 UTC, ggggkkkknnnn commented on paddlers/transforms/operators.py
这里的修改应该pre-commit进行的格式修改，我看修改都是删除行末的空格。辛苦您了

2023-03-23 12:19 UTC, Bobholamovic commented on paddlers/transforms/operators.py
看起来好像是把`operators.py`整个文件给删除了，请检查一下是不是之前误删了~
![image](https://user-images.githubusercontent.com/21275753/227201700-fa689505-f3fb-4445-bdde-9eadfd3a28a3.png)

2023-03-23 12:19 UTC, Bobholamovic commented on docs/intro/model_cons_param_en.md
但是因为我们是post在GitHub上的，所以请确保符合GitHub的markdown语法

2023-03-23 13:11 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_en.md
已将五个文档全部修改，符合Github的markdown语法

2023-03-23 13:12 UTC, ggggkkkknnnn commented on paddlers/transforms/operators.py
之前误删了，已经重新push了，修改的地方都是删除原来行末的空格。

2023-03-24 03:18 UTC, ggggkkkknnnn commented
请帮我review一下，谢谢您。

2023-03-24 05:53 UTC, Bobholamovic requested changes
请根据review意见修改。如果你有不同的意见或者需要补充说明，可以直接在conversation回复~

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `use_mixed_loss (bool, optional)` | 是否使用多种损失函数进行训练 | `False`      |
『多种损失函数』->『混合损失函数』

请同步修改PR中的其它位置。

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `**params` | 其他模型参数，例如卷积核大小、滤波器数量等。具体取决于模型的实现。 | - |
这个统一去掉吧，`*args`和`**kwargs`参数可以不用体现在文档里~

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `backbone (str, optional)` | 用作主干的ResNet体系结构。目前仅支持'resnet18'和'resnet34' | `'resnet18'` |
『用作主干的ResNet体系结构』->『用作主干网络的ResNet型号』

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `n_stages (int, optional)` | 主干中使用的ResNet阶段数，应为{3、4、5}中的值 | `4`          |
『主干』->『主干网络』

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `use_tokenizer (bool, optional)` | 是否使用分词器 | `True`       |
是否使用可学习的tokenizer

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `token_len (int, optional)` | 输入令牌的长度 | `4`          |
『令牌』->『token』。
在没有业界公认的准确翻译的情况下，请保留英文原词/词组。
请同步检查并修改其它位置。

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `att_type (str, optional)` | 空间注意力类型，可选值为'CBAM'和'BAM' | `'CBAM'`     |
`'CBAM'`、`1`、`True`等常量在表示代码意义时（如这里说的参数『可选值』），都需要用反引号包围。请同步检查并修改PR中其它位置。

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `enc_head_dim (int, optional)` | 每个编码器头部的嵌入维度 | `64`         |
head翻译为『头』即可。
请检查并修改PR中其它部分。

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `dec_depth (int, optional)` | 解码器中使用的注意力块数 | `8`          |
『注意力块数』->『注意力模块数量』

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `num_classes`  | 分类数目，通常为二分类问题       | `2`        |
『通常为二分类问题』是什么意思呢？

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `num_classes`  | 分类数目，通常为二分类问题       | `2`        |
另外，请统一`num_classes`、`in_channels`、`use_mixed_loss`、`losses`等各个模型都有的参数的释义（例如`in_channels`现在有时候解释为『输入通道数』，有时候解释为『输入图像波段数』）。

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `scale_factor`          | 上采样因子，用于缩放输出分割掩码的大小      | `4.0`       |
『用于缩放输出分割掩码的大小』-> 『用于缩放网络预测输出』

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `model_name`   | 模型名称                          | `'CDNet'`  |
为什么会有这个参数呀？

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `n_feats (int)`                        | 残差块中的特征数量 | `16`  |
『特征数量』->『特征维度』

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `negval (float)`                       | 非线性映射中的负值 | `0.2` |
这个感觉没有解释清楚，具体指的是什么呢？

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `lq_loss_weight (float)`               | 低质量图像损失的权重 | `0.1` |
『低质量图像损失』具体是什么损失？

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `sr_factor (int)` | 超分辨率的缩放因子，原始图像的大小将乘以此因子。例如，如果原始图像为 `H` x `W`，则输出图像将为 `sr_factor * H` x `sr_factor * W`。 | `4` |
各模型对`sr_factor`参数的解释也需要统一。

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `losses (List)` | 要使用的损失函数列表，如果`use_mixed_loss`为True | `None` |
`List`和`Tuple`建议统一使用PaddleRS docstring风格，即使用小写字母开头的`list`和`tuple`。如果对容器内部元素类型有要求，可以写作类似`list[int]`的格式。

请同步检查并修改PR中的其它位置。

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +基于PaddlePaddle的FarSeg实现
缺少句号。
请同步检查并修改PR中的其它位置。

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `align_corners (bool)` | 在双线性插值中是否使用像素中心对齐 | `False` |
请统一不同模型对`align_corners`的解释。另外，请确认这里的解释是否正确：`align_corners`为`True`时，将按照角点对齐还是按照像素中心对齐？

2023-03-24 05:53 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `test_pre_nms_top_n (int)` | 测试时，进行 NMS 操作之前保留的预测框的数量。如果未指定，则使用 `keep_top_k`。 | `None` |
目前此文档中有的地方在英文单词前后空格，有的地方没有。请保持风格一致。

2023-03-24 09:23 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `lq_loss_weight (float)`               | 低质量图像损失的权重 | `0.1` |
在单张图像超分辨率任务中，模型需要将低分辨率的输入图像恢复成高分辨率的输出图像。`lq_loss_weight`控制了在训练过程中低质量图像损失的相对重要性，即用于控制低分辨率输入图像的重建误差对总体损失的贡献程度。

2023-03-24 09:25 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `negval (float)`                       | 非线性映射中的负值 | `0.2` |
negval是一个浮点数参数，通常用于激活函数中的负数值的处理。在深度学习中，激活函数是一种非线性变换函数，常用于神经网络中。常见的激活函数包括sigmoid、ReLU、tanh等。

2023-03-24 09:27 UTC, ggggkkkknnnn commented
已进行修改

2023-03-24 09:43 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `negval (float)`                       | 非线性映射中的负值 | `0.2` |
> negval是一个浮点数参数，通常用于激活函数中的负数值的处理。在深度学习中，激活函数是一种非线性变换函数，常用于神经网络中。常见的激活函数包括sigmoid、ReLU、tanh等。

这样的话这里是不是应该表述为：用于设置非线性激活函数对负数输入的激活值。

2023-03-24 09:44 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `lq_loss_weight (float)`               | 低质量图像损失的权重 | `0.1` |
所以指的是『重建损失』嘛？

2023-03-24 09:54 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `negval (float)`                       | 非线性映射中的负值 | `0.2` |
我现在改为了”用于激活函数中的负数值的处理“，这个参数的主要作用就是对负数进行截断处理，例如这里的默认值0.2，则所有小于0的数值都会被截断为0.2，大于等于0的数值不变。

2023-03-24 09:59 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `lq_loss_weight (float)`               | 低质量图像损失的权重 | `0.1` |
低质量图像损失是将低分辨率的输入图像恢复成高分辨率的输出图像的重构损失，这个参数是一个权重参数，用来控制这个重构误差对于总体损失的影响程度。

2023-03-25 02:10 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `lq_loss_weight (float)`               | 低质量图像损失的权重 | `0.1` |
嗯嗯，这样的话请在参数描述里说清楚吧

2023-03-25 03:20 UTC, ggggkkkknnnn commented
已将`Supplementary description of `lq_loss_weight` parameter`的参数描述进行补充

2023-03-25 03:48 UTC, Bobholamovic commented
发现先前轮次已接受的review意见并未完全得到落实。例如，

> List和Tuple建议统一使用PaddleRS docstring风格，即使用小写字母开头的list和tuple

保证PR质量是最重要的，因此，请确认对先前轮次的review意见已经完全修改完毕后再请求review，否则我们可能会花费更多时间。为避免遗漏，后续将在先前review意见均已收到回复或完全得到落实的前提下继续给出新的review意见，感谢理解~

另外，建议可以对已经完成修改的review意见逐条回复『done』，以减小遗漏的可能性。

2023-03-25 03:50 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `negval (float)`                       | 非线性映射中的负值 | `0.2` |
好的

2023-03-25 05:13 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `align_corners (bool)` | 在双线性插值中是否使用像素中心对齐 | `False` |
done

2023-03-25 05:42 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +##BIT
done

2023-03-25 05:43 UTC, ggggkkkknnnn commented on .idea/.gitignore
done

2023-03-25 05:43 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +#PaddleRS中每个模型的构造参数
done

2023-03-25 05:43 UTC, ggggkkkknnnn commented on paddlers/transforms/operators.py
done

2023-03-25 05:44 UTC, ggggkkkknnnn commented on .gitignore
> +.idea
done

2023-03-25 05:44 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +|`in_channels (int)`|输入图像的频带数|       |
done

2023-03-25 05:45 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +| 数据变换算子名                | 用途                                                     | 任务     | ... |
done

2023-03-25 05:45 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +对输入施加随机模糊
done

2023-03-25 05:45 UTC, ggggkkkknnnn commented on .gitignore
> +#myidea
done

2023-03-25 05:45 UTC, ggggkkkknnnn commented on .gitignore
> +
done

2023-03-25 05:45 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +本文档详细介绍了PaddleRS各个模型训练器的构造参数，包括其参数名，参数类型，参数描述及默认值。
done

2023-03-25 05:45 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_en.md
done

2023-03-25 05:45 UTC, ggggkkkknnnn commented on tutorials/train/README.md
> +```shell
done

2023-03-25 05:46 UTC, ggggkkkknnnn commented on paddlers/transforms/operators.py
done

2023-03-25 05:46 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `use_mixed_loss (bool, optional)` | 是否使用多种损失函数进行训练 | `False`      |
done

2023-03-25 05:47 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `backbone (str, optional)` | 用作主干的ResNet体系结构。目前仅支持'resnet18'和'resnet34' | `'resnet18'` |
done

2023-03-25 05:47 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `n_stages (int, optional)` | 主干中使用的ResNet阶段数，应为{3、4、5}中的值 | `4`          |
done

2023-03-25 05:47 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `use_tokenizer (bool, optional)` | 是否使用分词器 | `True`       |
done

2023-03-25 05:47 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `token_len (int, optional)` | 输入令牌的长度 | `4`          |
done

2023-03-25 05:47 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `att_type (str, optional)` | 空间注意力类型，可选值为'CBAM'和'BAM' | `'CBAM'`     |
done

2023-03-25 05:47 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `enc_head_dim (int, optional)` | 每个编码器头部的嵌入维度 | `64`         |
done

2023-03-25 05:47 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `dec_depth (int, optional)` | 解码器中使用的注意力块数 | `8`          |
done

2023-03-25 05:48 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `num_classes`  | 分类数目，通常为二分类问题       | `2`        |
done

2023-03-25 05:48 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `scale_factor`          | 上采样因子，用于缩放输出分割掩码的大小      | `4.0`       |
done

2023-03-25 05:48 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `model_name`   | 模型名称                          | `'CDNet'`  |
已删除，done

2023-03-25 05:48 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `n_feats (int)`                        | 残差块中的特征数量 | `16`  |
done

2023-03-25 05:48 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `sr_factor (int)` | 超分辨率的缩放因子，原始图像的大小将乘以此因子。例如，如果原始图像为 `H` x `W`，则输出图像将为 `sr_factor * H` x `sr_factor * W`。 | `4` |
done

2023-03-25 06:01 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +基于PaddlePaddle的FarSeg实现
done

2023-03-25 06:04 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `test_pre_nms_top_n (int)` | 测试时，进行 NMS 操作之前保留的预测框的数量。如果未指定，则使用 `keep_top_k`。 | `None` |
done

2023-03-25 06:07 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `losses (List)` | 要使用的损失函数列表，如果`use_mixed_loss`为True | `None` |
done

2023-03-25 06:08 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `num_classes`  | 分类数目，通常为二分类问题       | `2`        |
已修改，done

2023-03-27 01:25 UTC, ggggkkkknnnn commented
已全部修改，麻烦review

2023-03-27 08:12 UTC, Bobholamovic requested changes
请根据意见修改或回复。

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `decoder_softmax (bool)`       | 是否使用`softmax`作为解码器的最后一层激活函数 | `False`      |
这里的`softmax`不是变量名、函数名或常量，只是一个学术上的概念，所以应该不需要添加反引号

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `in_channels (int)` | 模型的输入通道数      | int | `3` |
这里好像还未统一

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/model_cons_param_en.md
> +| `num_classes (int)`     | Number of classes, usually for binary classification problems                                      | `2` |
这里未统一表述

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/model_cons_param_en.md
> +| `dual_loss_weight (float)`              | The weight of the bilateral loss
建议对`description`一栏开头的定冠词是否省略统一风格，避免`Number of image channels`和`The weight of the bilateral loss`同时存在。

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +|`gamma (bool，可选)`| 是否使用 `gamma` 校正 | `False` |
gamma校正为学术名词，不是所有的英文单词都要用反引号包围哈

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +|`method (str，可选)`| 用于匹配双时间图像亮度的方法。选项有{`'hist'`， `'lsr'`， `'fft`}。`“hist”`代表直方图匹配，`“lsr”`代表最小二乘回归，`“fft”`替换图像的低频分量以匹配参考图像  | `"hist"` |
请统一一下双引号和单引号

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +| `mean (list[float]/ tuple[float]，可选)`     | 输入图像的均值                          | `[0.485,0.456,0.406]` |
按照PaddleRS已有文档中的类型注释风格，『或』应该用『|』而不是『/』

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +| `apply_to_tar (bool，可选)`                  | 是否对目标图像应用转换                      | `True`                         |
『应用转换』->『应用数据变换算子』

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +| `thresholds (list[float]，可选)`            | Iou 阈值，用于决定有效的 bbox 裁剪           | `[.0,.1， .3， .5， .7， .9]` |
Iou的正确写法为IoU。请同步检查并修改PR中的其它位置。

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +|`probb (float)`| 模糊的概率 |      |
typo：probb -> prob
请同步检查并修改PR中的其它位置。

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +| `cover_all_box (bool，可选)`        | 是否确保在最终裁剪中覆盖所有盒子                 | `False`                   |
请注意避免机翻，如『盒子』

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +| `Target_sizes (list[int] / list[list /tuple] /tuple [list /tuple])` | 多个目标大小，每个目标大小应该是`int`、`list`或`tuple`  | `.5`                  |
这里的默认值是不是写错了呀？

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +| `short_sizes (list[int])` | 图像较短一侧的目标大小| `.5`  |
这里的默认值好像也不对。请同步检查并修改PR中的其它位置。

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_cn.md
> +| `band_list (list，可选)` | 要选择的波段(波段索引从1开始) | `[1,2,3]`  |
中文句子中请使用中文（全角）括号

2023-03-27 08:12 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_en.md
请同步修改`docs/intro/transforms_cons_params_cn.md`中的意见。

2023-03-27 08:12 UTC, Bobholamovic commented on tutorials/train/README.md
> +## 模型精度验证
这个部分还没有实现相应的脚本，应该以代码块形式教学如何调用`model.evaluate()` API进行精度验证。

2023-03-27 08:12 UTC, Bobholamovic commented on tutorials/train/README.md
> +## 模型部署
部署部分已经有相关文档，贴一下指向模型导出和部署文档的链接即可。

2023-03-27 08:12 UTC, Bobholamovic commented on tutorials/train/README.md
这个文件存在于`tutorials/train`目录中，且标题为`使用教程——训练模型`。因此，将模型验证和部署内容放在这个文档中是不合适的。

请考虑在`docs`目录中新建`quick_start.md`文档，填写此文档中现有内容（标题改为`快速开始`）。训练和推理部分只要给出相应文档的链接（比如训练部分就给`tutorials/train/README.md`的链接），不必再拷贝一次内容，验证部分需要补充。

最后，将项目根目录下README中『快速上手PaddleRS』链接改为指向新的quick start文档。

2023-03-27 08:37 UTC, Bobholamovic commented
此外，也辛苦把表格的列标题改为首字母大写的形式吧，与已有的文档统一风格。

2023-03-27 11:31 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `decoder_softmax (bool)`       | 是否使用`softmax`作为解码器的最后一层激活函数 | `False`      |
done

2023-03-27 11:31 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_cn.md
> +| `in_channels (int)` | 模型的输入通道数      | int | `3` |
done

2023-03-27 11:47 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +|`probb (float)`| 模糊的概率 |      |
done

2023-03-27 11:47 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +| `thresholds (list[float]，可选)`            | Iou 阈值，用于决定有效的 bbox 裁剪           | `[.0,.1， .3， .5， .7， .9]` |
done

2023-03-27 11:47 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +| `apply_to_tar (bool，可选)`                  | 是否对目标图像应用转换                      | `True`                         |
done

2023-03-27 11:47 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +| `mean (list[float]/ tuple[float]，可选)`     | 输入图像的均值                          | `[0.485,0.456,0.406]` |
done

2023-03-27 11:47 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +|`method (str，可选)`| 用于匹配双时间图像亮度的方法。选项有{`'hist'`， `'lsr'`， `'fft`}。`“hist”`代表直方图匹配，`“lsr”`代表最小二乘回归，`“fft”`替换图像的低频分量以匹配参考图像  | `"hist"` |
done

2023-03-27 11:48 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +|`gamma (bool，可选)`| 是否使用 `gamma` 校正 | `False` |
done

2023-03-27 11:48 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_en.md
> +| `dual_loss_weight (float)`              | The weight of the bilateral loss
done

2023-03-27 11:48 UTC, ggggkkkknnnn commented on docs/intro/model_cons_param_en.md
> +| `num_classes (int)`     | Number of classes, usually for binary classification problems                                      | `2` |
done

2023-03-27 11:48 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +| `cover_all_box (bool，可选)`        | 是否确保在最终裁剪中覆盖所有盒子                 | `False`                   |
done

2023-03-27 11:48 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +| `Target_sizes (list[int] / list[list /tuple] /tuple [list /tuple])` | 多个目标大小，每个目标大小应该是`int`、`list`或`tuple`  | `.5`                  |
done

2023-03-27 11:51 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +| `short_sizes (list[int])` | 图像较短一侧的目标大小| `.5`  |
done

2023-03-27 11:51 UTC, ggggkkkknnnn commented on docs/intro/transforms_cons_params_cn.md
> +| `band_list (list，可选)` | 要选择的波段(波段索引从1开始) | `[1,2,3]`  |
done

2023-03-27 11:52 UTC, ggggkkkknnnn commented on tutorials/train/README.md
done

2023-03-27 11:55 UTC, ggggkkkknnnn commented
> 此外，也辛苦把表格的列标题改为首字母大写的形式吧，与已有的文档统一风格。

已将英文文档表格列标题修改

2023-03-28 06:40 UTC, ggggkkkknnnn commented
麻烦请review一下，谢谢您~

2023-03-28 08:08 UTC, Bobholamovic requested changes
1. 上一轮review意见中提到的部分修改尚未完成： 
![image](https://user-images.githubusercontent.com/21275753/228168772-cde9a9a4-ff51-4e09-b5e4-f112966b8682.png)
![image](https://user-images.githubusercontent.com/21275753/228168985-d88c7ade-a030-4ac1-910f-e0d15ed57024.png)

2. 我先前对『表格列标题首字母大写』的表述有歧义，其实是希望能改写为类似文档标题那样的每个实词都首字母大写的格式，例如`Parameter Name`，而不只是『句首字母大写』。另外我注意到目前各个英文文档的标题好像也没有遵照这个规则，也请一并改写一下。例如：`PaddleRS Model Construction Parameters`。

3. 在markdown表格中插入`|`字符需要转义，否则无法正常渲染（请在GitHub查看`docs/intro/transforms_cons_params_cn.md`目前的渲染效果）。

2023-03-28 09:20 UTC, ggggkkkknnnn commented
已完成修改~

2023-03-28 10:05 UTC, Bobholamovic requested changes
留了一些意见

2023-03-28 10:05 UTC, Bobholamovic commented on docs/intro/model_cons_param_cn.md
> +| `sr_factor (int)   `       | 超分辨率的缩放因子，原始图像的大小将乘以此因子。例如，如果原始图像为 `H` x `W`，则输出图像将为 `sr_factor * H` x `sr_factor * W` | `4`   |
`sr_factor (int) `第二个反引号前有3个多余的空格。

2023-03-28 10:05 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_en.md
> +# PaddleRS Data Transform Operator Construct Parameter
`PaddleRS Data Transform Operator Construct Parameter` -> `PaddleRS Data Transformation Operator Construction Parameters`

2023-03-28 10:05 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_en.md
> +This document describes the parameters of each PaddleRS data transform operator in detail, including the operator name, operator purpose, parameter name, parameter type, parameter meaning, and parame
1. `transform operator` -> `transformation operator`。
2. `Default Value`需要首字母小写，请不要在句中随意进行首字母大写。

2023-03-28 10:05 UTC, Bobholamovic commented on docs/quick_start.md
> +### 2. python部署
python的规范写法为Python

2023-03-28 10:05 UTC, Bobholamovic commented on docs/quick_start.md
> +### 1. 导出模型
『导出模型』->『模型导出』

2023-03-28 10:05 UTC, Bobholamovic commented on docs/quick_start.md
> +导出模型可见：[模型导出](./deploy/export/README.md)
模型导出可参考：[部署模型导出](./deploy/export/README.md)

2023-03-28 10:05 UTC, Bobholamovic commented on docs/quick_start.md
> +python部署可见：[Python部署](./deploy/README.md)
Python部署可参考：

2023-03-28 10:05 UTC, Bobholamovic commented on docs/quick_start.md
> +本目录中整理了使用PaddleRS训练模型的示例代码。代码中均提供对示例数据的自动下载，并均使用GPU对模型进行训练。
> 本目录中整理了使用PaddleRS训练模型的示例代码。

『本目录』是`docs`，其中并没有『整理了使用PaddleRS训练模型的示例代码』。这样的说法让读者感到疑惑。

此外，不建议大段拷贝其它文档中的内容，因为这会导致文件内容冗余，从而使项目可维护性降低（后续如果有一处文档需要改动，就不得不同步修改两个地方）。

请去除此部分。

2023-03-28 10:05 UTC, Bobholamovic commented on docs/quick_start.md
> +### 1. 导出模型
标题样式不统一。一级标题没有编号，二级标题却使用了一级标题编号。建议统一不使用编号，或者一级标题使用`1. 标题`风格编号，二级标题使用`1.1 子标题`风格编号。

2023-03-28 10:05 UTC, Bobholamovic commented on docs/quick_start.md
> +## 环境准备
请勿大段拷贝其它文档中的内容，理由同上。请使用引用链接代替。

2023-03-28 10:05 UTC, Bobholamovic commented on docs/quick_start.md
> ++ 模型训练可参考：[使用教程——训练模型](./tutorials/train/README.md)
当前目录为`docs`，其中并没有`./tutorials`子目录，因此该链接应该是无效的。

请同步检查PR中涉及到的**所有**链接，修改无效的链接。

2023-03-28 14:45 UTC, ggggkkkknnnn commented
已针对您提出的建议进行修改~

2023-03-29 06:09 UTC, Bobholamovic commented on docs/intro/transforms_cons_params_en.md
> +# PaddleRS Data Transformation Operator Construct Parameters
`Construct`->`Construction`

2023-03-29 06:11 UTC, Bobholamovic commented on docs/quick_start.md
> +python部署可参考：[Python部署](../deploy/README.md)
`python` -> `Python`

2023-03-29 07:03 UTC, ggggkkkknnnn commented on docs/quick_start.md
> +python部署可参考：[Python部署](../deploy/README.md)
done

2023-03-29 07:03 UTC, ggggkkkknnnn commented
已完成修改

2023-03-29 07:07 UTC, Bobholamovic approved these changes
LGTM.

2023-03-29 07:08 UTC, Bobholamovic commented
我们将在CI通过后合入此PR。

再次感谢你为PaddleRS贡献文档，以及对PR review工作的配合。

2023-03-29 07:32 UTC, merged

2023-03-29 08:12 UTC, Harryoung commented
不容易啊！顺利合入了！为ggggkkkknnnn的耐心和坚持点个赞！也为我们负责review的研发同学的认真和负责点赞！！！
开源项目需要这样的精神！飞桨因你们更精彩！

2023-06-07 11:09 UTC, Ligoml commented
@ggggkkkknnnn 开发者你好，第四期飞桨黑客松已全部结束，进入荣誉&奖金发放阶段，有一些信息需要与你收集与确认，请尽快添加工作人员的微信，备注黑客松+队名，他会拉你进群，感谢配合~
<img src="https://github.com/PaddlePaddle/PaddleRS/assets/39876205/ecc90d98-5361-4db9-a70d-816c2a777f65" width = "400" alt="wechat"/>

2023-06-13 08:24 UTC, Ligoml commented
@ggggkkkknnnn 开发者您好，请尽快添加我们的工作人员微信，如果在6.20之前无法确认您的信息，我们将不再进行奖金发放，本任务算作自发贡献。