feature->add changeformer model
PaddlePaddle/PaddleRS pull request #13
Opened 2022-08-09 04:56 UTC by kongdebug

### PR types

### PR changes

### Description

2022-08-09 05:00 UTC, kongdebug commented
![464df78c2486d29953658411222c99b](https://user-images.githubusercontent.com/52785738/183568064-5534bbc9-7417-4fbb-a679-fff9f6c5f36e.png)

2022-08-09 05:29 UTC, kongdebug commented
TIPC测试完整时间戳
![1e8fd153d0eb76a3c9f22deb4ce9d42](https://user-images.githubusercontent.com/52785738/183571530-bc289fbf-f90d-4d0a-864b-942fa79cf996.png)
![790e37fb07ec42c5e9ddcac7cc0a99e](https://user-images.githubusercontent.com/52785738/183571546-ff6ecfd7-fb8c-4c37-845e-5cf089aa913a.png)
![afc059eaa209166489819e5a1bb3560](https://user-images.githubusercontent.com/52785738/183571568-ac8c761f-2f6f-4581-8049-1e9dd82dd903.png)
![87c501693b582040eece88ece4837b5](https://user-images.githubusercontent.com/52785738/183571591-820698b6-22e3-4a03-a85a-f4b10a537a77.png)

2022-08-09 09:05 UTC, Bobholamovic requested changes
未按[《贡献指南》](https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/CONTRIBUTING.md)要求添加单测，请添加相关代码并保证本地测试通过。

2022-08-09 09:05 UTC, Bobholamovic commented on tutorials/train/change_detection/changeformer.py
> +# 变化检测模型BIT训练示例脚本
注释没有修改

2022-08-09 09:05 UTC, Bobholamovic commented on tutorials/train/change_detection/changeformer.py
> +# 使用默认参数构建BIT模型
注释没有修改。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/tasks/change_detector.py
> +class ChangeFormerV6(BaseChangeDetector):
ChangeFormer作者确定的最终版本就是ChangeFormerV6，我理解从易用性出发考虑，是否对外暴露的训练器API直接叫做ChangeFormer就好？

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/tasks/change_detector.py
> +                 input_nc=3,
`input_nc`和其它训练器统一一下名字，应该叫`in_channels`。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +        #         reflection_padding = kernel_size // 2
去除未使用的注释。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +class ConvBlock(pd.nn.Layer):
`paddlers.rs_models.cd.layers`中是否有可以复用的模块？

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +class EqualLR:
`EqualLR`以及`equal_lr`好像没有在其他地方用到，应该去除。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +from .layers.pd_timm import DropPath, to_2tuple
`pd_timm`代表的是？

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +        # Transformer Encoder
super()之后加一个空行

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +        self.depths = [3, 3, 4, 3]  # [3, 3, 6, 18, 3]
这个注释是什么意思？

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +    def __init__(self,
缺少docstring，请添加。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +            # trunc_normal_(m.weight, std=.02)
去除无关注释。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +        """Transform inputs for decoder.
请按照PaddleRS的注释格式要求编写。
例如，`"""`之后应该要另起一行。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +        return [outputs[-1]]
不建议把返回列表的需求放在`Decoder`中实现，建议Decoder还是直接返回Tensor，只是在最外层的`ChangeFormerV6`的`forward`中返回列表以满足接口要求。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +        # pdb.set_trace()
去除所有pdb相关内容，包括注释。

2022-08-09 09:05 UTC, Bobholamovic commented on paddlers/rs_models/cd/changeformer.py
> +class Attention_dec(nn.Layer):
请斟酌命名应该为`Attention_dec`还是`AttentionDec`。`Block_dec`等类似。

2022-08-10 01:32 UTC, kongdebug commented
> 未按[《贡献指南》](https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/CONTRIBUTING.md)要求添加单测，请添加相关代码并保证本地测试通过。

已添加，不过运行run_test.sh的时候还有一点问题，今天麻烦晖哥帮看一下，我会在群里提出

2022-08-10 15:23 UTC, Bobholamovic approved these changes
LGTM，但请回答一下conversation中遗留的问题。

2022-08-10 15:56 UTC, kongdebug commented
> LGTM，但请回答一下conversation中遗留的问题。

辛苦晖哥，已在上面回答

2022-08-11 03:12 UTC, merged

2022-08-11 03:13 UTC, Bobholamovic commented
精度验收通过，代码符合规范，论文复现成功。