Automatically generate file list
PaddlePaddle/PaddleRS pull request #133
Opened 2023-04-12 13:14 UTC by huilin16

### PR types

Others
### PR changes

Tools
### Description

Automatically generate file list

2023-04-20 02:26 UTC, Bobholamovic requested changes
因为这个`tools/prepare_dataset/common.py`中的API主要是针对开发者的，一般用户没有感知，建议仿照`tools/prepare_dataset`中的其它脚本，以独立脚本的形式提供file list的生成功能，在过程中可以使用`tools/prepare_dataset/common.py`中的其它API，并且更新相关的中英文文档~

2023-04-20 02:28 UTC, huilin16 commented
ok

2023-04-20 11:37 UTC, Bobholamovic commented
我的锅，之前没注意这个脚本被放在`tools/prepare_dataset`中了，而这个文件夹里主要是放开源数据集预处理脚本，file list生成脚本应该直接放在`tools`中。我做了这一修改，另外也顺便加了一些先前漏掉的copyright，辛苦根据`generate_file_lists.py`脚本更新一下中英文文档~

2023-04-20 12:06 UTC, huilin16 commented
好的

2023-04-21 07:31 UTC, Bobholamovic approved these changes
LGTM.

2023-04-21 07:31 UTC, merged