Uniform code style of tools and fix docs of tools
PaddlePaddle/PaddleRS pull request #138
Opened 2023-04-20 06:52 UTC by huilin16

### PR types

Code refactoring
### PR changes

Tools
### Description

Update variable names and uniform the code style of tools

2023-04-20 08:57 UTC, Bobholamovic requested changes
赞👍 这个PR的工作量很大，感谢贡献~ 留了一些小建议，请参考comments内容

2023-04-20 08:57 UTC, Bobholamovic commented on docs/data/coco_tools_cn.md
> +| `--Args_show` | （可选）是否打印输入参数信息            | `True` |
`Args_show`选项如果没有用到了，请移除。请同步检查并修改其它位置。

2023-04-20 08:57 UTC, Bobholamovic commented on docs/data/coco_tools_cn.md
> +    --pic_shapeRate_path=./img_sta/images_shapeRate.png
这个参数是不是应该叫`pic_shape_rate_path`呀？同理还有`pic_posEnd_path`。请检查并修改选项中的驼峰命名法。

2023-04-20 08:57 UTC, Bobholamovic commented on docs/data/coco_tools_cn.md
> +    --pic_shapeRate_path=./img_sta/images_shapeRate.png
请问这里区分picture和image是有意的吗？

2023-04-20 08:57 UTC, Bobholamovic commented on tests/tools/run_coco_tools.py
请问`tests`中的脚本测试过是ok的嘛？

2023-04-20 08:57 UTC, Bobholamovic commented on tools/coco_tools/json_anno_sta.py
> +    parser.add_argument("--json_path", type=str, required=True, \
请根据`docs/data/coco_tools_en.md`修改`tools/coco_tools`的各脚本中命令行选项的help信息。对默认值的表述方式为`Defaults: None`。help字符串结尾需添加句号。例如：
`help="Path for the statistics table. If None, do not save. Default: None."`

2023-04-20 09:00 UTC, huilin16 commented on docs/data/coco_tools_cn.md
> +| `--Args_show` | （可选）是否打印输入参数信息            | `True` |
好的，忘记修改了，这就更正

2023-04-20 09:00 UTC, huilin16 commented on docs/data/coco_tools_cn.md
> +    --pic_shapeRate_path=./img_sta/images_shapeRate.png
是的，也是在doc中忘记修改了

2023-04-20 09:02 UTC, huilin16 commented on docs/data/coco_tools_cn.md
> +    --pic_shapeRate_path=./img_sta/images_shapeRate.png
输入路径是没有特别的用意，就是用之前的demo直接输入了

2023-04-20 09:05 UTC, huilin16 commented on tests/tools/run_coco_tools.py
我这边运行不了run_script以及run_tests.sh，只把run_script中的命令在命令行中测试过了

2023-04-20 09:06 UTC, huilin16 commented on tools/coco_tools/json_anno_sta.py
> +    parser.add_argument("--json_path", type=str, required=True, \
好的

2023-04-20 09:08 UTC, huilin16 commented on docs/data/coco_tools_cn.md
> +    --pic_shapeRate_path=./img_sta/images_shapeRate.png
那我也跟参数一样改成pic_shape_rate吧

2023-04-20 12:05 UTC, huilin16 commented on docs/data/coco_tools_cn.md
> +    --pic_shapeRate_path=./img_sta/images_shapeRate.png
我想起来了之前用png是想用png表示保存的结果是个png文件，但是保存的图谱可以是任意格式图片，所以改成了pic，然输入路径的images表示是图片的shape，这样好像确实有歧义，要不把参数名和路径都改成img_shape_rate_path, img_shape_rate.png这样吧

2023-04-20 12:45 UTC, huilin16 commented
变量名都已改为下划线命名法，cocotools中的help信息已更新，‘Args_show’在说明文档中已删除，

关于--pic_shapeRate_path=./img_sta/images_shapeRate.png的pic、images还没有做修改

2023-04-20 12:50 UTC, Bobholamovic commented on docs/data/coco_tools_cn.md
> +| `--Args_show` | （可选）是否打印输入参数信息            | `True` |
ok

2023-04-20 12:50 UTC, Bobholamovic commented on docs/data/coco_tools_cn.md
> +    --pic_shapeRate_path=./img_sta/images_shapeRate.png
好的

2023-04-20 12:50 UTC, Bobholamovic commented on tests/tools/run_coco_tools.py
没事儿，那我这边来测一下~

2023-04-20 13:25 UTC, huilin16 commented
把关于图片统计结果的图片路径改为了img_开头，把关于对象统计结果的图片路径改为了obj_开头

2023-04-21 04:00 UTC, Bobholamovic approved these changes
我修改了一些小细节，现在应该可以合入啦~ 再次感谢贡献！

2023-04-21 04:00 UTC, merged