refine rotated object detector
PaddlePaddle/PaddleRS pull request #146
Opened 2023-05-09 03:51 UTC by Asthestarsfalll

### PR types

Bug fixes
### PR changes

Others
### Description

修复#100中旋转目标检测的问题，添加PPYOLOE—R

2023-05-09 04:42 UTC, Bobholamovic reviewed
这个设计可以的，我觉得ok

2023-05-09 04:42 UTC, Bobholamovic commented on paddlers/tasks/object_detector.py
> +            reg_coeff (float, optional): Coefficient for L2 weight decay regularization.
需同步更新文档

2023-05-09 04:59 UTC, Asthestarsfalll commented on paddlers/tasks/object_detector.py
> +            reg_coeff (float, optional): Coefficient for L2 weight decay regularization.
已更新

2023-05-09 05:00 UTC, Asthestarsfalll commented
修复了DarkNet53的问题，同时重构了一下backbone的检查。

2023-05-09 05:06 UTC, Asthestarsfalll commented on tutorials/train/object_detection/ppyoloe_r.py
> +    "https://paddlers.bj.bcebos.com/datasets/dota.zip", path="./data/")
另外这里的数据集似乎需要添加一下

2023-05-10 09:26 UTC, Asthestarsfalll commented
ppyoloe-r训练结果，使用前600多样本
![2023-05-10_17-25](https://github.com/PaddlePaddle/PaddleRS/assets/72954905/bb84b9fe-fe6d-41ca-a342-3e86fbbd7903)

2023-05-10 12:38 UTC, Asthestarsfalll commented
ppyoloe_r训练结果，这里保存路径忘改了
![2023-05-10_17-25](https://github.com/PaddlePaddle/PaddleRS/assets/72954905/e0ce5ee3-2385-45b2-b433-407ec80c61e0)

2023-05-10 12:40 UTC, Bobholamovic requested changes
目前除了旋转框检测模型的脚本，其它的检测模型的tutorial好像都跑不起来了……辛苦在修改代码后验证一下原有模型是否能够跑通，咱们要确保新增模型不会破坏已有模型哈~

2023-05-10 12:40 UTC, Bobholamovic commented on paddlers/tasks/base.py
> +                if self.model_name in ['PicoDet', 'PPYOLOE_R']:
这里让基类依赖于子类感觉不是很优雅。如果没有更好的解决方案的话，可以加个`# TODO: Refactor` 注释先标记一下。

2023-05-10 12:40 UTC, Bobholamovic commented on paddlers/tasks/base.py
> +                if self.model_name in ['PicoDet', 'PPYOLOE_R']:
另外这里是为什么需要进行这个操作呀？

2023-05-10 12:40 UTC, Bobholamovic commented on tutorials/train/object_detection/ppyolo.py
> +    metric='rbox',
这里是为啥需要修改哦？

2023-05-10 12:40 UTC, Bobholamovic commented on tutorials/train/object_detection/ppyoloe_r.py
> +train_transforms = T.Compose([
建议可以去除`T.Compose`以及`T.BatchCompose`，和其它tutorials保持相同风格。

2023-05-10 12:40 UTC, Bobholamovic commented on paddlers/tasks/object_detector.py
我发现上个PR对batch transforms的重构好像有一定问题，原先的行为是用户指定的batch transforms会和内置的batch transforms混合，现在好像变成了要么用custom要么用default了……可能需要修改一下保证行为不变。

2023-05-10 12:42 UTC, Asthestarsfalll commented on tutorials/train/object_detection/ppyolo.py
> +    metric='rbox',
加错文件了...

2023-05-10 12:42 UTC, Asthestarsfalll commented on tutorials/train/object_detection/ppyoloe_r.py
> +train_transforms = T.Compose([
了解

2023-05-10 12:59 UTC, Asthestarsfalll commented on paddlers/tasks/base.py
> +                if self.model_name in ['PicoDet', 'PPYOLOE_R']:
这里是因为这两个网络需要在不同的训练阶段使用不同的assigner。
https://github.com/PaddlePaddle/PaddleRS/blob/dfd50caf860202336e47f6bdcc7dd1863f2f85aa/paddlers/models/ppdet/modeling/heads/pico_head.py#L653-L674

https://github.com/PaddlePaddle/PaddleRS/blob/dfd50caf860202336e47f6bdcc7dd1863f2f85aa/paddlers/models/ppdet/modeling/heads/ppyoloe_r_head.py#L260-L283

注意到dataset有`set_epoch`方法，可以考虑直接在__get_item__里面设置

2023-05-10 13:02 UTC, Asthestarsfalll commented on paddlers/tasks/object_detector.py
如果是混合的话就不能和ppdet中进行对齐了，而且这是否是用户已知的行为，个人认为未指定就使用默认比较好，混合似乎会对用户造成一定困扰（如果是我的话）

2023-05-10 13:08 UTC, Asthestarsfalll commented on paddlers/tasks/object_detector.py
> +        super(YOLOv3, self).__init__(
之前的方法似乎有些多余，因此还是修改为类似其他继承YOLO3的方法。

2023-05-10 13:10 UTC, Asthestarsfalll commented on paddlers/utils/checkpoint.py
> +
这里的改动是因为CSPResNet的权重都少了一个`backbone.`

2023-05-10 13:13 UTC, Bobholamovic commented on paddlers/tasks/object_detector.py
这个地方原先确实有些问题，在用户不知情的情况下加入了和修改了一些东西，我能想到的唯一的好处可能就是：减轻用户配置的负担（用户不用手动加这些可能是『必须要有』的变换，也不用关心`collate_batch`应该设置为True还是False）。从编程的角度来说，我不喜欢这样『隐式』的行为，我十分赞成变量的名字和功能应该匹配。

不过，在我们修改了代码的行为之后，原有的tutorial脚本跑不起来了（因为原有的脚本基于这种『混合』的行为），我想这应该是一件更大的事——代码好看了，但是用不了。从重构的角度来说，我想我们不算成功，因为重构不应该改变代码外在的行为。为了解决这个『更严重』的问题，我有两个方案，我们可以讨论一下：
1. 保持优雅的代码设计，即，要么使用用户定义的batch_transforms，要么使用默认的。这种方式需要我们修改tutorials脚本中的示例代码，让它们能够基于新的API跑通。风险在于我们可能会发现，tutorials脚本变得异常复杂，对用户极不友好，而这违背了PaddleRS产品的原则，之后我们又要进一步思考如何隐藏一些细节，让用户使用起来『更简单』。
2. 偷个懒，改回原先的逻辑，让两种transforms按照原有的方式混合，hard-code那些collate_batch，以确保tutorials脚本不必变动就能跑出原来的效果。这样的缺点在于我们不得不接受重构前的那个丑陋的设计，并且这个设计造成的负面影响将继续存在。

2023-05-10 13:15 UTC, Bobholamovic commented on paddlers/tasks/base.py
> +                if self.model_name in ['PicoDet', 'PPYOLOE_R']:
如果需要在这里进行的话也是OK的，可以在注释里稍微标注一下原因。

2023-05-11 02:17 UTC, Bobholamovic commented on paddlers/tasks/object_detector.py
> +        super(YOLOv3, self).__init__(
OK

2023-05-11 02:35 UTC, Bobholamovic commented on paddlers/utils/checkpoint.py
> +
`BaseModel.initialize_net`有一个`is_backbone_weights`参数，是不是可以在`BaseDetector`里改造一下？

2023-05-11 03:42 UTC, Asthestarsfalll commented on paddlers/utils/checkpoint.py
> +
已修改

2023-05-11 08:02 UTC, Asthestarsfalll commented
不知道为什么这里的batch_transforms就是为None, COCODetDataset是正常的

https://github.com/PaddlePaddle/PaddleRS/blob/98af92f90079d442b2aa218500399caa684b71d2/tutorials/train/object_detection/faster_rcnn.py#L56-L62

2023-05-11 13:05 UTC, Bobholamovic commented on paddlers/tasks/object_detector.py
> +                BatchNormalizeImage(
`normalize`的部分不建议放在`_default_batch_transforms`中，因为定制归一化参数是比较常见的需求~

2023-05-12 10:30 UTC, Asthestarsfalll commented on paddlers/tasks/object_detector.py
> +                BatchNormalizeImage(
了解

2023-05-12 10:33 UTC, Asthestarsfalll commented on paddlers/tasks/object_detector.py
此处按照第二种方式修改

2023-05-12 12:27 UTC, Asthestarsfalll commented
教程脚本测试结果：
ppyoloe_r:
![2023-05-12_19-56](https://github.com/PaddlePaddle/PaddleRS/assets/72954905/83afcedb-1b9f-4960-830c-f6ba2d1f599b)
fcosr:
![2023-05-12_19-58](https://github.com/PaddlePaddle/PaddleRS/assets/72954905/29320535-5580-4b76-8a9d-bd988c68df97)
ppyolo_tiny:
![2023-05-12_20-04](https://github.com/PaddlePaddle/PaddleRS/assets/72954905/3087f7be-e5d8-4138-89ac-68e36ead2b9c)
yolov3:
![2023-05-12_20-08](https://github.com/PaddlePaddle/PaddleRS/assets/72954905/6c445da8-b572-49bf-a3f9-1d237716c10e)
ppyolov2:
![2023-05-12_20-16](https://github.com/PaddlePaddle/PaddleRS/assets/72954905/0677a8b8-2c71-4c3b-ac07-e3ebeec7d30e)
ppyolo：始终为0
faster rcnn：loss为nan

2023-05-13 09:03 UTC, Asthestarsfalll commented
faster rcnn:
![2023-05-13_16-43](https://github.com/PaddlePaddle/PaddleRS/assets/72954905/d60295a1-3dc1-456a-af6f-2acc5c158a3c)

2023-05-14 01:45 UTC, Asthestarsfalll commented on paddlers/tasks/object_detector.py
> +        return filtered
这里用于过滤default batch tansforms中与用户自定义的batch transforms的重复项

2023-05-16 03:08 UTC, Bobholamovic commented on paddlers/tasks/object_detector.py
> +        return filtered
OK

2023-05-16 03:46 UTC, merged