Fccdn final
PaddlePaddle/PaddleRS pull request #23
Opened 2022-08-21 17:53 UTC by liuxtakeoff

# 运行结果总览：
![9](https://user-images.githubusercontent.com/71876619/185804262-f93a6d1f-ef6e-4d44-a980-0d28708a02bb.png)
# tipc全过程：
![1](https://user-images.githubusercontent.com/71876619/185804261-59ae81c8-8b7d-477e-a391-cdb82c58a28e.png)
![2](https://user-images.githubusercontent.com/71876619/185804352-379b4d84-67a1-476a-8e4d-d0f349910d60.png)
![3](https://user-images.githubusercontent.com/71876619/185804358-450fd1d3-f55d-4d79-9c5d-cb2e5ba31d9b.png)
![4](https://user-images.githubusercontent.com/71876619/185804361-0f6ee53e-2e20-4ffd-99e2-58e934e87628.png)
![5](https://user-images.githubusercontent.com/71876619/185804364-837026b5-9530-4d8b-b957-c1dd6bd8db72.png)
![6](https://user-images.githubusercontent.com/71876619/185804368-b897eb5a-e840-4b00-a6b4-478a40df1fa7.png)
![7](https://user-images.githubusercontent.com/71876619/185804373-17cef584-1fae-470a-99d3-bda0d5f3ed98.png)
![8](https://user-images.githubusercontent.com/71876619/185804377-d46d929f-a71b-43ed-a994-a1e4f81c2fc2.png)

2022-08-22 08:12 UTC, Bobholamovic requested changes
我认为bcd loss和普通的交叉熵应该解耦，也即模型在training模式下应该有两个输出：第一个输出是最终的logits，用来计算交叉熵；第二个是用来计算自监督损失所需要的输入。这样设计之后会方便用户进行loss组合。

2022-08-22 08:12 UTC, Bobholamovic commented on tutorials/train/change_detection/fccdn.py
> +# 目前已支持的模型请参考：https://github.com/PaddlePaddle/PaddleRS/blob/develop/docs/apis/model_zoo.md
无效的URL

2022-08-22 14:10 UTC, liuxtakeoff commented
已按照要求对损失函数进行了解耦，并修改了链接及描述。

2022-08-23 02:24 UTC, Bobholamovic requested changes
TIPC耗时太长，lite_train_lite_infer训练过程应该保持在10分钟以内，建议调参并减小epoch数。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/fccdn.py
> +        in_channels(int): Number of input channels(default: 3).
括号和单词之间需要1个空格。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/fccdn.py
> +    """dense connection-based feature fusion module"""
首字母大写。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/fccdn.py
> +class DensecatCatDiff(nn.Layer):
DensecatCatDiff还是DenseCatDiff？为什么有两个cat

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/fccdn.py
> +from paddlers.rs_models.cd.layers import BasicConv, MaxPool2x2, Conv1x1, Conv3x3
使用相对引用，直接`from .layers import ...`即可。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/__init__.py
> +from .losses import fccdn_loss_ssl
建议名字直接叫`ssl_loss`。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +            weight: paddle.Tensor,
如果其它的函数都没有用type hint，那我建议保持风格统一这里也不需要用。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +        if self.do_sigmoid:
为什么写的是`do_sigmoid`，实际功能却是do softmax？

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    def __call__(self, y_true, y_pred):
不建议直接重写`nn.Layer`对象的`__call__`方法。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    def __call__(self, y_pred, y_true):
有的loss把`y_pred`放在前面、`y_true`放在后面，有的则不是。建议统一把pred放前面gt放后面。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +class DiceBceLoss(nn.Layer):
名字应该叫`DiceBCELoss`

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    """Binary loss"""
这个注释没有描述清楚类的功能，只从`binary`这个词并得不到太多信息。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +
此处无需空行。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +class McDiceBceLoss(nn.Layer):
`Bce`->`BCE`

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    out1[labels_downsample == 1] = 0
注意数值类型。此时`labels_downsample`的dtype为`paddle.float32`，由于[浮点误差](https://www.zhihu.com/question/380574329)的存在，不建议直接对浮点型使用`==`、`!=`、`<=`等运算符。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    # Get downsampled change map
为了增强通用性，建议可以修改为将`labels` resize到`scores[0]`大小。

2022-08-23 02:24 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    pred_seg_pre_tmp1 = paddle.ones(out1.shape)
类似的写法使用`paddle.where`实现是否更优雅一些？另外可以通过记录mask来防止每次都要重新计算二值索引用的mask。

2022-08-23 07:09 UTC, liuxtakeoff commented on paddlers/rs_models/cd/fccdn.py
> +class DensecatCatDiff(nn.Layer):
他命名逻辑是有两种Densecat，一个是cat_diff,就叫Densecat_cat_diff;一个是cat_add就叫Densecat_cat_add。似乎叫DenseCatDiff更简明些，晚上修改一下。

2022-08-23 07:10 UTC, liuxtakeoff commented on paddlers/rs_models/cd/__init__.py
> +from .losses import fccdn_loss_ssl
但这样会不会无法体现这是fccdn里的损失，如果后续添加了其他自监督损失就无法区分了呀

2022-08-23 07:16 UTC, liuxtakeoff commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    # Get downsampled change map
除了池化方法我没查找到其他resize tensor的方法。。resize方法好像是不能改变数据数目的，只能改变数据的形状，从[3,10,10] -> [3,20,5]这样，似乎做不到[3,10,10]->[3,5,5]。

2022-08-23 07:19 UTC, liuxtakeoff commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +        if self.do_sigmoid:
这个应该是作者写错了，我修改一下

2022-08-23 07:21 UTC, liuxtakeoff commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    def __call__(self, y_true, y_pred):
那是改为forward方法吗

2022-08-23 08:12 UTC, liuxtakeoff commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    # Get downsampled change map
或许我可以加一个判断报错？如果labels和scores[0]尺寸不一样了，就报错提示用户“尺寸错误，请检查网络输入是否为16的倍数”

2022-08-23 09:22 UTC, Bobholamovic commented on paddlers/rs_models/cd/__init__.py
> +from .losses import fccdn_loss_ssl
好的，这样的话请修改为`fccdn_ssl_loss`吧，命名上一般`loss`放最后。

2022-08-23 09:22 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    def __call__(self, y_true, y_pred):
是的

2022-08-23 09:23 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    # Get downsampled change map
可以看一下`paddle.nn.functional.interpolate()`函数。

2022-08-24 08:54 UTC, liuxtakeoff commented
对训练参数进行了调整，最终训练轮次为15，训练时间在10分钟之内。
![train1](https://user-images.githubusercontent.com/71876619/186374915-5a988fa7-0830-46c4-9ca9-676f999838f7.png)
![train2](https://user-images.githubusercontent.com/71876619/186374941-5c485803-844c-4fc4-8aa1-04bee989bbcc.png)
鉴于可以节省的计算量不大，就没有创建mask记录索引值，其他都按要求进行了调整。

2022-08-25 02:28 UTC, Bobholamovic reviewed
精度验收通过，TIPC满足要求，代码基本满足规范，论文复现成功。再做一些格式上的小修改后可以合入PR。

2022-08-25 02:28 UTC, Bobholamovic commented on paddlers/rs_models/cd/fccdn.py
> +        in_channels (int): Number of input channels(default: 3).
`(default: ...)`这个括号也要注意空格。

2022-08-25 02:28 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +    out1 = paddle.where(labels_downsample == 1, paddle.zeros_like(out1), out1)
这里可以加一个断言，判断labels_downsample的dtype为integral类型，防止潜在错误。

2022-08-25 02:28 UTC, Bobholamovic commented on test_tipc/configs/cd/fccdn/fccdn.yaml
> +
去除多余的空行，参考原来的yaml中的排布。

2022-08-25 07:45 UTC, Bobholamovic reviewed
之前有些忽略的细节，请修改一下~

2022-08-25 07:45 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
> +        f"Expect labels type int or bool, but the type is {labels_type}"
f"Expected dtype of `labels` to be int or bool, but got {labels_type}."

2022-08-25 07:45 UTC, Bobholamovic commented on paddlers/rs_models/cd/losses/fccdn_loss.py
>      FCCDN change detection self-supervised learning loss
输入看起来是logits而不是scores（因为后面又做了sigmoid）。另外因为这个API要暴露给用户，所以需要按照docstring的格式要求撰写注释。例如：
```
Self-supervised learning loss for change detection.

The original article refers to
    Pan Chen, et al., "FCCDN: Feature Constraint Network for VHR Image Change Detection"

Args:
    logits_list (list[paddle.Tensor]): Single-channel segmentation logit maps for each of the two temporal phases.
    labels (paddle.Tensor): Binary change labels.
```

2022-08-25 08:37 UTC, liuxtakeoff commented on paddlers/rs_models/cd/losses/fccdn_loss.py
>      FCCDN change detection self-supervised learning loss
已按要求进行修改~

2022-08-26 02:38 UTC, Bobholamovic approved these changes
LGTM.

2022-08-26 02:39 UTC, merged