Factseg paddle
PaddlePaddle/PaddleRS pull request #54
Opened 2022-10-12 11:46 UTC by LHE-IT

### PR types
 New features 

### PR changes
Models

### Description
Add the FactSeg model and its TIPC in paddle, which has passed offical precision verification and  finished the test in PaddleRS. The output log was included in the config directory.

2022-10-12 12:51 UTC, LHE-IT commented
我添加的模型代码位于PaddleRS\paddlers\rs_models\seg\factseg.py，在本地可以通过风格审查，其他代码为fork的原生代码，通过和技术人员交流其他代码风格要求可能与PaddleRS不同，因此只需核验添加代码即可

2022-10-12 13:56 UTC, LHE-IT commented
Thank you for your commit. I have use the official pre-commit-config.yaml and sorry for change this file.

2022-10-13 03:36 UTC, Bobholamovic commented
There is problem with linting. Please check the code style.

2022-10-13 06:28 UTC, Bobholamovic requested changes
我提交了两个commit，修复了代码风格。
代码方面需要做一些修改。
另外，请提供迁移到PaddleRS后的模型与先前仓库/AI Studio中实现的模型一致的证明。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/tasks/segmenter.py
> +                 num_classes=16,
`num_classes`默认设置为2。

2022-10-13 06:28 UTC, Bobholamovic commented on test_tipc/configs/seg/factseg/factseg_rsseg.yaml
> +# Configurations of FarSeg with RSSeg dataset
注释没有配套修改。

2022-10-13 06:28 UTC, Bobholamovic commented on test_tipc/configs/seg/factseg/results_python.log
> +------------------------ lite_train_lite_infer ------------------------
新增内容中不应该包含`.log`文件，请去除。

2022-10-13 06:28 UTC, Bobholamovic commented on tests/rs_models/test_seg_models.py
> +        self.targets = [[self.get_zeros_array(16)], [self.get_zeros_array(10)],
`self.specs`有三项，而`self.targets`却有五项，二者不对应。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/rs_models/seg/factseg.py
> +def conv_with_kaiming_uniform(use_gn=False, use_relu=False):
请评估能否复用`paddlers.rs_models.seg.layers.param_init.py`中的初始化方法以及`paddlers.rs_models.seg.layers.layers_lib.py`中的基础模块。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/rs_models/seg/factseg.py
> +class FPN(nn.Layer):
请评估能否复用`paddlers.rs_models.seg.farseg.py`中的FPN实现。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/rs_models/seg/factseg.py
> +class ResNetEncoder(nn.Layer):
请评估能否复用paddlers.rs_models.seg.farseg.py中的ResNetEncoder实现。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/rs_models/seg/factseg.py
> +class AssymetricDecoder(nn.Layer):
请评估能否复用`paddlers.rs_models.seg.farseg.py`中的`AsymmetricDecoder`实现。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/rs_models/seg/factseg.py
> +
去除多余的空行。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/rs_models/seg/factseg.py
> +            in_channels=3,
`in_channels`和`num_classes`无需设置默认值。需要对应修改注释。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/rs_models/seg/factseg.py
> +         backbone_pretrained (bool): Whether the backbone network uses IMAGENET
对于有默认值的注释，需要在类型说明里添加`optional`，例如`backbone_pretrained (bool, optional)`。

2022-10-13 06:28 UTC, Bobholamovic commented on paddlers/rs_models/seg/factseg.py
> +from paddlers.models.ppdet.modeling import initializer as init
为何使用检测套件的模型初始化？

2022-10-13 06:37 UTC, LHE-IT commented on paddlers/rs_models/seg/factseg.py
> +from paddlers.models.ppdet.modeling import initializer as init
原始模型的初始化就是直接copy的检测套件的初始化脚本，并非复现了torch的init

2022-10-13 07:13 UTC, LHE-IT commented on paddlers/rs_models/seg/factseg.py
> +def conv_with_kaiming_uniform(use_gn=False, use_relu=False):
通过查看paddler.rs_models.seg.layer.param_init.py和layer_lib.py的初始化源码，发现它们使用的是nn.initialize进行初始化，而非像检测套件一样重写torch的初始化函数，经过个人验证，这样初始化会与torch产生较大偏差。 conv_with_kaiming_uniform中的是否添加Relu需要根据参数变化，layers_lib.py中的ConvRelu有一定差异，且ConvRelu没有采用kaiming初始化方法，个人认为不能使用上述两个脚本的基础模块

2022-10-14 10:15 UTC, LHE-IT commented on paddlers/rs_models/seg/factseg.py
> +from paddlers.models.ppdet.modeling import initializer as init
![image](https://user-images.githubusercontent.com/65936492/195820158-96ac351b-4909-4979-9955-39ebfc1c798f.png)
![6$9S2VLTX 3P(_3RPMMD7SD](https://user-images.githubusercontent.com/65936492/195822491-89130c08-d942-4654-8d0c-0f2963fc850b.png)
已经在github和Aistudio上传了新版本，并从模型结构对齐和测试集上精度对齐两方面验证了迁移模型和原来模型的一致性。该模型由于复用了FarSeg的模块，模块名有所改变，请使用/home/aistudio/model_rs_verify/torch2paddleFactSeg_RS.py脚本进行迁移模型权重转换

2022-10-14 10:51 UTC, LHE-IT commented on paddlers/tasks/segmenter.py
> +                 num_classes=16,
已修改

2022-10-14 10:51 UTC, LHE-IT commented on test_tipc/configs/seg/factseg/factseg_rsseg.yaml
> +# Configurations of FarSeg with RSSeg dataset
已修改

2022-10-14 10:51 UTC, LHE-IT commented on test_tipc/configs/seg/factseg/results_python.log
> +------------------------ lite_train_lite_infer ------------------------
已修改

2022-10-14 10:51 UTC, LHE-IT commented on tests/rs_models/test_seg_models.py
> +        self.targets = [[self.get_zeros_array(16)], [self.get_zeros_array(10)],
已修改

2022-10-14 10:52 UTC, LHE-IT commented on paddlers/rs_models/seg/factseg.py
> +         backbone_pretrained (bool): Whether the backbone network uses IMAGENET
已修改

2022-10-14 10:52 UTC, LHE-IT commented on paddlers/rs_models/seg/factseg.py
> +            in_channels=3,
已修改

2022-10-14 10:52 UTC, liuhongen1234567 commented on paddlers/rs_models/seg/factseg.py
> +
已修改

2022-10-14 10:53 UTC, LHE-IT commented on paddlers/rs_models/seg/factseg.py
> +class AssymetricDecoder(nn.Layer):
已修改

2022-10-14 10:54 UTC, Bobholamovic commented
Please resolve the conflicts.

2022-10-14 13:45 UTC, Bobholamovic approved these changes
LGTM.

2022-10-14 13:49 UTC, Bobholamovic commented
TIPC验证通过，运行时间满足要求：
![image](https://user-images.githubusercontent.com/21275753/195862304-e094ff5a-ac80-4a98-bde1-99db9607aca7.png)

2022-10-14 14:06 UTC, Bobholamovic commented
更新了文档，添加tutorial。

2022-10-14 14:24 UTC, Bobholamovic commented
精度验证通过，仓库符合规范，PR满足要求，论文复现成功。

2022-10-14 14:24 UTC, merged